### ISSUE TITLE
How do I do Error Reporting?

### ISSUE THREAD

**Issue by nahtnam** [fastify/fastify-cli#122]
Hello!

Currently, I am trying to set up Sentry with my fastify server. I am doing the following:

```js
fastify.setErrorHandler(function (error, request, reply) {
  Sentry.captureException(error, { request });
})
```

However, I noticed that adding this makes the server not respond to the requests. I was wondering if it were possible to add this `captureException` line but also respond to fastify in the default manner?

**Comment by delvedor** [comment]
Hi! You should also call `reply.send(error)`, that API is meant to update the error if needed.
What you need will land in Fastify v2 :) https://github.com/fastify/fastify/pull/1236

**Comment by nahtnam** [comment]
Awesome, thank you!

**Comment by nahtnam** [comment]
@delvedor One more question, do you know how to get the status code in the setErrorHandler function? I would only like to report errors in the 500 range.

**Comment by delvedor** [comment]
You can access it from `reply.res.statusCode` :)
