### ISSUE TITLE
Default test paths for the template

### ISSUE THREAD

**Issue by witkwski** [fastify/fastify-cli#124]
If Fastify assumes the recursive folder structure, why wouldn't change the default test paths from `tap test/*.test.js test/*/*.test.js test/*/*/*.test.js` to `tap test/**/*.test.js` for the template, because it ignores nested plugin/service folders

**Comment by cemremengu** [comment]
It does not look like it's ignoring them but I agree that is more concise
```
$ npm run test

> test@1.0.0 test C:\Users\cemre.mengu\Desktop\test
> tap test/*.test.js test/*/*.test.js test/*/*/*.test.js

test/plugins/support.test.js .......................... 2/2 823ms
test/services/example.test.js ......................... 2/2 806ms
test/services/root.test.js ............................ 2/2 798ms
total ................................................. 6/6
```
