### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by patrickcurl** [fastify/fastify-cli#136]
Installed globally via NPM and Yarn, same issue. 
When I run any fastify command I get the error: 
/usr/bin/env: ‘node\r’: No such file or directory

Arch Linux (Antergos)
Node: 10.11.0
Yarn: 1.12.3
NPM: 6.4.1

**Comment by patrickcurl** [comment]
k, I found a fix..  appears it's the space between #! and /usr/bin/env node ... 
I submitted a pull request to fixt hat... https://github.com/fastify/fastify-cli/pull/137

**Comment by cemremengu** [comment]
Can your problem be this https://askubuntu.com/a/1053068 ?

@mcollina do we really need this line?

**Comment by patrickcurl** [comment]
I don't think that's my issue, namely because I use NVM, and node is in my path... but maybe fastify somehow goes outside nvm's shims trying to find a different node to use? I'm not 100% on how that works specifically... .. I mean I can use node -v and if I just clone the project, and run node cli.js -- it throws the same error, if I run it after removing the space, then it works fine.

**Comment by cemremengu** [comment]
I see, thanks for investigating. I was just trying to find out if there was some other cause for it.

**Comment by cemremengu** [comment]
@patrickcurl thank you for the PR! I will be patching this on npm in an hour

**Comment by patrickcurl** [comment]
Sure no problem... glad to help.
