### ISSUE TITLE
Error: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by lynxionxs** [fastify/fastify-cli#138]
When installing the cli via npm, ```sudo npm install fastify-cli --global``` and running ```fastify generate``` i get the following error ```/usr/bin/env: ‘node\r’: No such file or directory```
What is wrong?

OS: Ubuntu 18.04
NPM VERSION: v5.4.2
NODE VERSION: v8.7.0

**Comment by cemremengu** [comment]
@lynxionxs can you try the latest patch to see if that resolves your issue? (v0.26.2)

**Comment by lynxionxs** [comment]
@cemremengu i reinstalled and its working fine now. Thanks

**Comment by cemremengu** [comment]
Thanks for letting us know!
