### ISSUE TITLE
Watch mode crash when start server if we use fastify-nextjs

### ISSUE THREAD

**Issue by meotimdihia** [fastify/fastify-cli#149]
Watch mode crash when start server if we use the fastify-nextjs plugin.

**Comment by meotimdihia** [comment]
I think the two is incompatible in this case: 
![conemu64_2019-01-26_15-29-11](https://user-images.githubusercontent.com/300961/51784681-3bd6b200-217f-11e9-839b-49ae2057d6d0.png)

(My code is working if I remove --watch option.)

**Comment by mcollina** [comment]
I think you have to exclude some temp directory of nextjs with `--ignore-watch=`

**Comment by meotimdihia** [comment]
After I ignoring .next directory, it's working now. Thanks :)
