### ISSUE TITLE
Environment variable FASTIFY_WATCH is not honored

### ISSUE THREAD

**Issue by simov** [fastify/fastify-cli#151]
The reason why is because `require('dotenv').config()` is not called inside the `start()` function, and therefore

```js
if (opts.watch) {
  return watch(args, opts.ignoreWatch)
}
```

is never true, unless there is an actual CLI argument set for it.

Unfortunately putting `require('dotenv').config()` on top of the `start()` function breaks your test suite. So probably there is something else going on that I'm not aware of.

---

My `.env` file looks like this:

```bash
FASTIFY_WATCH=true
```

And I'm starting the server with:

```bash
fastify start server.js
```

**Comment by cemremengu** [comment]
Yes looks like this is a bug, I will look into it as well. Feel free to send a PR if you come up with a solution in the meantime.

**Comment by cemremengu** [comment]
See `v0.27.1`

**Comment by mariusa** [comment]
This happens again. This should be moved back to top?
https://github.com/fastify/fastify-cli/blob/master/start.js#L62
