### ISSUE TITLE
prefix register twice

### ISSUE THREAD

**Issue by compasss** [fastify/fastify-cli#159]
I'm create project by this command: `fastify generate test`
and start project by `fastify start -l info -P -w app.js -r /chat-api `

fastify-cli file start.js line 129 register fastify  _routePrefix
``` javascript
if (opts.prefix) {
    pluginOptions.prefix = opts.prefix
    fastify._routePrefix = opts.prefix || ''
}
```
fastify-autoload options config register prefix again

i have to access app by this url http://127.0.0.1:3000/chat-api/chat-api/example
what i need is http://127.0.0.1:3000/chat-api/example

**Comment by Eomm** [comment]
Could you just remove `-r /chat-api` from `fastify start` commands?

**Comment by compasss** [comment]
change app.js file and remove `-r /chat-api` from fastify start commands solved problem。
```js
  // This loads all plugins defined in services
  // define your routes in one of these
  opts.prefix = '/chat-api'
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'services'),
    options: Object.assign({}, opts)
  })
```
