### ISSUE TITLE
support for async-await plugins

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-cli#16]
As titled, fastify now supports them!

**Comment by dottorblaster** [comment]
Hi!

Do you mean something like this as an async/await plugin?

```js
'use strict'

module.exports = function (fastify, options, next) {
  fastify.get('/', async function (req, reply) {
    var res = await new Promise(function (resolve) {
      setTimeout(resolve, 200, { hello: 'world' })
    })
    return res
  })
  next()
}
```

**Comment by delvedor** [comment]
Hi @dottorblaster!
Nope, he means that the plugin can use async/await, so:
```js
'use strict'

module.exports = async function (fastify, options) {
  fastify.get('/', async function (req, reply) {
    return { hello: 'world' }
  })
}
```

Checkout [avvio](https://github.com/mcollina/avvio) if you want to see how we handle plugins :)

**Comment by dottorblaster** [comment]
Nice! Giving this a shot as soon as possible 😉 Thanks for the support!

**Comment by mcollina** [comment]
Done

**Comment by dottorblaster** [comment]
![Perfect!](https://media.giphy.com/media/Rr3lgUreqh5V6/giphy.gif)

**Comment by giovanni-bertoncelli** [comment]
I haven't found anything in the docs: an async plugin should not use the `done` parameter then? It has only to wait that the promise resolves, right?

**Comment by alemagio** [comment]
Exactly.
You can see an example [here](https://github.com/fastify/fastify-cli/blob/master/templates/app/plugins/support.js)
