### ISSUE TITLE
a new fastify app generator?

### ISSUE THREAD

**Issue by davidedantonio** [fastify/fastify-cli#161]
Hi all,
I've created a Fastify app generator inspired to this wonderful project and I called it [create-fastify-app](https://github.com/davidedantonio/create-fastify-app). Create Fastify App can help a programmer to generate or add plugin to a Fastify project. For now I added these functionalities:

- Generate a Fastify Project, also from a given swagger file.
- Generate a service skeleton in existing Fastify Project.
- Add Cors plugin in existing Fastify Project.
- Add MongoDB plugin in existing Fastify Project.
- Add Redis plugin in existing Fastify Project. 

I hope to be able to add many other plugins and features!
What do you think? It might be useful to the Fastify community?

**Comment by mcollina** [comment]
I think it would be extremely helpful for the community. I’m not sure how to recommend this because we have a generator in fastify-cli.

What do @fastify/fastify think?

**Comment by Ethan-Arrowood** [comment]
FWIW I’ve also been working on a fastify app generator (ethan-arrowood/Matterhorn),  but mine focuses on TypeScript and additional JS app tooling. 

Maybe we can start a list of Fastify app generators? List the features for each one so the users can pick whichever best suited their developer needs

**Comment by Eomm** [comment]
> List the features for each one so the users can pick whichever best suited their developer needs

This is a good idea, maybe this could help devs to adopt fastify or build and share news plugins.
I love feature-tables: clear and intuitive.

**Comment by evanshortiss** [comment]
👍 sounds great, in the future I'd imagine it might be nice to have a standard (like `create-react-app`) based on whichever is favoured by the community?
