### ISSUE TITLE
More control over logging

### ISSUE THREAD

**Issue by temsa** [fastify/fastify-cli#162]
@mcollina It seems that we currently need to `eject` if we want more control over the logger, e.g.:
- [ ] force the pino logger instance so we can use the logger out of fastify context
- [ ] set our own configuration, notably what to `redact` or serializers

It could be great if that would not be necessary ( an env var for loading a module exporting the logger could be enough, and some example in the Readme )

**Comment by mcollina** [comment]
I think having this would be amazing. I've tagged it as "good first contribution", if there is somebody that would be willing to work on it sooner than what we could provide.

**Comment by francisbrito** [comment]
Is it ok if I have a look at this one?

@temsa @mcollina would something along the lines of `FASTIFY_LOGGING_MODULE=<path_to_logging_module_file.js>` work?

Should the module export an object confirming the "Pino Interface", a function returning a Pino-interface-compatible object or any of the two?

**Comment by mcollina** [comment]
> Should the module export an object confirming the "Pino Interface", a function returning a Pino-interface-compatible object or any of the two?

How about the whole `logger` configuration for the fastify instance? That seems flexible enough.

**Comment by francisbrito** [comment]
Sounds good, I'll proceed to open a PR.
