### ISSUE TITLE
error occurs when writting files inside application directory with 'fastify start --watch'

### ISSUE THREAD

**Issue by tranzwalle** [fastify/fastify-cli#168]
I writting a file under the appliction directory, like 'cache/filecache.json',
and start the application with command 'fastify start --log-level info --pretty-logs app.js'.
If the file was changed, an error will show in terminal, "[fastify-cli] process forced end"

of course, this error can be avoided by '--ignore-watch'.
But when I use nodemon, there's no such error, so I submit this

**Comment by tranwalle** [comment]
<img width="386" alt="fastify-cli-err" src="https://user-images.githubusercontent.com/8072111/56414187-60dd4b80-62bc-11e9-8eb9-d1bc6c28c6fb.png">

**Comment by mcollina** [comment]
Ouch! Would you like to send a PR to fix this?

**Comment by tranwalle** [comment]
OK, it maybe take times, I haven't read the source code.
As a new user of fastify, I think 'fastify-cli' shoud be simple and can be integrated with other awesome tools.  How about let PM2 and nodemon to take over the feature of '--watch'

**Comment by zuck** [comment]
Same here. Any hint about what could generate this issue?

**Comment by mcollina** [comment]
No clue, it would be good to have an example, even better a PR with a failing test.

**Comment by zuck** [comment]
It's definitely an issue with big files changing inside the folder the CLI is watching. In my case was a SQLite DB file.

The workaround is the same mentioned above, just use the `--ignore-watch FILE_NAME` option to _fix_ it.

**Comment by whoisjuan** [comment]
@mcollina This went stale, but definitely a still problem. Writing a file inside the application directory crashes the CLI. This also makes you lose visibility of any logs that happen between the process ending and the server restarting to listen.

**Comment by mariusa** [comment]
+1 still an issue, shouldn't be closed

**Comment by mariusa** [comment]
I'm curious if this is a bug. I came here because I didn't know what caused it. After seeing the cause, `FASTIFY_IGNORE_WATCH` was the proper solution. If this were present in the error message ` process forced end`, it would have saved me time.

I believe `--watch` does what it asked, to watch for changes and restart fastify. Changing a file and complaining it restarts shouldn't be an issue, but the error message should mention the cause & solution.

**Comment by Eomm** [comment]
> I'm curious if this is a bug

Me too 😄

We don't have a failing error test or something that we can just execute to reproduce the error. I'm using `fastify-cli` and I did not hit this error, so I can't invest too much time to replicate it.

I _assume_ that to solve this case `It's definitely an issue with big files changing inside the folder the CLI is watching`, we need a timeout before starting the reloading process.

I totally agree that it would be great to improve the error message as the first step!

**Comment by whoisjuan** [comment]
I think this is a bug because running it with an unwrapped node process doesn't produce this exception. Also, writing a file into the app directory is a fairly common practice to deal with temp files and other situations where it is not convenient to keep artifacts in memory.

My expectation is that the fastify-cli should try to mirror standard server behavior as much as possible.

**Comment by mcollina** [comment]
Maybe somebody could produce some code to replicate the problem?

**Comment by uki1014** [comment]
@mcollina 

I could reproduce this problem using this minimal repository.
https://github.com/uki1014/fastify-cli_issue168

Details of the reproduction procedure are below.

1. launch server `npm run dev` and check localhost:3000.
2. change `return { root: true };` in `src/routes/root.ts` to `return { root: 'foo' };` and make sure compile and fastify are reloaded again.
3. change `return { root: 'foo' };` to `return { root: 'bar' };` and wait for a while without doing anything, then you will see `[App] [fastify-cli] process forced end`' will appear in the console.

Not related to this issue, but I noticed that if I check locahost:3000 immediately after changing the ts file and re-compiling, get 503. (If I then wait a bit and check again, there is no problem. There seems to be some time lag.)
