### ISSUE TITLE
If imported file throw a wrong error is shown in console

### ISSUE THREAD

**Issue by allevo** [fastify/fastify-cli#18]
Consider file "myserver.js"
```js
undefinedVariable.pippo.pluto.paperino = 5
```

`fastify myserver.js` throws a wrong error ("Cannot find the specified file ....")

Maybe a check [here](https://github.com/fastify/fastify-cli/blob/master/cli.js#L47) on `error.code` is needed

**Comment by delvedor** [comment]
Pr? :)

**Comment by allevo** [comment]
I'll :smile:
