### ISSUE TITLE
Where must I register any module ?

### ISSUE THREAD

**Issue by siddiquiehtesham** [fastify/fastify-cli#180]
I am trying to use fastify-formbody and I am using it as a standalone server by adding the server.js files as mentioned in the fastify-cli docs.
I tried to register fastify-formbody in app.js as well as server.js but i always get null in the request.

**Comment by mcollina** [comment]
Would you mind uploading a full snippet?

**Comment by siddiquiehtesham** [comment]
Oops it seemed to be a mistake I was accessing it in a GET Method request.
Now it works properly as I am using POST method request.

**Comment by Eomm** [comment]
Closing since it is solved now

Feel free to reopen if needed
