### ISSUE TITLE
Throws error on providing a file that doesn't exist with start command

### ISSUE THREAD

**Issue by jamesgeorge007** [fastify/fastify-cli#181]
`fastify start <file>` throws an error if the respective file doesn't exist:-

![Screenshot from 2019-06-22 23-02-21](https://user-images.githubusercontent.com/25279263/59967020-2acd7980-9542-11e9-934b-581a3e98475d.png)

It seems that this was intentional as from:-
 https://github.com/fastify/fastify-cli/blob/f8ca00c1066c779b822b315a07162098fe41b161/start.js#L91

IMO it is good to warn the user appropriately :thinking:

**Comment by jamesgeorge007** [comment]
@mcollina I would submit a PR if this makes sense to you.

**Comment by mcollina** [comment]
Go for it!

Il giorno sab 22 giu 2019 alle ore 19:37 James George <
notifications@github.com> ha scritto:
