### ISSUE TITLE
Switch the generated project to use async/await by default

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-cli#183]
As titled, Node 6 is deprecated, so we do not have to support callbacks anymore.

This would be a semver-major change.

**Comment by xtx1130** [comment]
I will make `generate.js` and `generate-readme.js` export promisify `generate`

**Comment by iandrc** [comment]
@mcollina this one could be closed, I guess

**Comment by mcollina** [comment]
Yes thanks!
