### ISSUE TITLE
Maybe add Mocks inside tests/helper 

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify-cli#191]
Hello everyone.

I created some projects with `fastify-cli` and most of them use simple "mocks". I bootstrapped the "mocks" inside build of the project, maybe add the mock function inside `helper.js` can help someone.

Example with `fastify-mongodb`:
```js
const Fastify = require('fastify')
const fp = require('fastify-plugin')
const App = require('../src/app')

// Fill in this config with all the configurations
// needed for testing the application
function config () {
  return {}
}

function mocks () {
  // Mocking fastify-mongodbb
  return (fastify, opts, next) => {
    fastify.decorate('mongo', {
      db: {
        collection (...any) {
          return this
        },
        count () {
          return new Promise((resolve, reject) => resolve([]))
        },
        find (...any) {
          return this
        },
        skip (...any) {
          return this
        },
        limit (...any) {
          return this
        },
        toArray () {
          return new Promise((resolve, reject) => resolve([]))
        }
      }
    })
    next()
  }
}

// automatically build and tear down our instance
function build (t) {
  const app = Fastify()

  // fastify-plugin ensures that all decorators
  // are exposed for testing purposes, this is
  // different from the production setup
  app.register(fp(mocks()))
  app.register(fp(App), config())

  // tear down our app after we are done
  t.tearDown(app.close.bind(app))

  return app
}
```

So, for add, just add it inside the project:
```js
// Fill with simple mocks.
function mocks () {
  return (fastify, opts, next) => {
  }
}
```

What do you think about it?  Bad usage? I created it because not need many configurations or use external libs like `Sinon` and the `tests` on route X not need use database by example, just return empty.

**Comment by xtx1130** [comment]
I am a bit confused about why you need to mock `fastify-mongodb` 's apis?

**Comment by RafaelGSS** [comment]
Just basic test inside routes without connection with the database. Insert/Select just returns and not throw an error, if the CI Pipeline that running the tests did not have knowledge of connection.

**Comment by RafaelGSS** [comment]
But, my idea is just add it inside `fastify-cli/tests/helper.js`: 

```
// Fill with simple mocks.
function mocks () {
  return (fastify, opts, next) => {
  }
}
```
And update build()

```
function build (t) {
  const app = Fastify()
  
  // Mocks basics
  app.register(fp(mocks()))

  // fastify-plugin ensures that all decorators
  // are exposed for testing purposes, this is
  // different from the production setup
  app.register(fp(App), config())

  // tear down our app after we are done
  t.tearDown(app.close.bind(app))

  return app
}
```

**Comment by mcollina** [comment]
I prefer to use real databases if I can control.. testing against mocks
does not make me much certain that the app would work in the real word. I
test with mocks to check error paths that are hard to check and verify with
a real db.

Il giorno mer 31 lug 2019 alle 16:35 Rafael Gonzaga <
notifications@github.com> ha scritto:

**Comment by xtx1130** [comment]
I'm -1 of it. If you mock db, It will cause you can't test your sql statements. Otherwise, if you need to test your routers, you can use `app.inject` to achieve it. If your need to contain db inside routers, use mock db can not ensure the real db connection and sql statements

**Comment by RafaelGSS** [comment]
Sure, I understand and think that I wrote wrong about my suggestion of feature.

Is just add the `mocks` function for anyone that need uses any mock (Sinon, etc...)

But, for now, maybe write the `mocks` (if necessary) inside "test" scope for each test is better.

Thanks all.
