### ISSUE TITLE
Use oclif as cli framework

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-cli#194]
Hi,
I have very good experiences with https://oclif.io/ it allows to build modular cli applications. All the common tasks like help generation, command/sub-command abstraction, flag, argument parsing or even a plugin architecture is already abstracted in a nice interface.

Some real-world examples:

- https://github.com/heroku/cli
- https://github.com/netlify/cli

It will reduce the burden to get familiar with our cli and make it much more maintainable when the cli gets bigger.

**Comment by xtx1130** [comment]
I have taken a look about the examples, but I didn't find more info about how to write test cases when using `oclif`.

**Comment by StarpTech** [comment]
Check out the official docs and at the end you can write tests as usual. Commands be run programmatically.

**Comment by mcollina** [comment]
I'm kind of +1 for this. I think the current set of features this provides us is a bit _too simple_ for what we actually need.

Do you plan to use TypeScript or JavaScript @StarpTech?

@jsumners what do you think?

**Comment by StarpTech** [comment]
> Do you plan to use TypeScript or JavaScript @StarpTech?
Personally, I prefer Javascript but for the community Typescript could be a valuable option. WDYT?

**Comment by mcollina** [comment]
I'm happy to stick with JavaScript.

**Comment by jsumners** [comment]
I don’t know anything about `fastify-cli`. My opinion would be useless here.

**Comment by xtx1130** [comment]
I'm +/-0 of it, I didn't find any unit tests about files in `commands` folder. All the test cases are  requesting interfaces and relate it to one command. It can't ensure the `run` method can run correctly in `Command` class. But I think it's base class `Command ` is what we needed.

**Comment by StarpTech** [comment]
@xtx1130 for example:
1. Run command
```
MyTestCommand.run([flags])
```
2. Mock stdout/stderr with [stdout-stderr](https://github.com/jdxcode/stdout-stderr)
3. Verify http calls with [nock](https://github.com/nock/nock)

- [@oclif/test](https://github.com/oclif/test)

**Comment by xtx1130** [comment]
@StarpTech Ops... I have understand what the test cases mean. [`.command(['foo:bar'])`](https://github.com/oclif/test/blob/master/test/command.test.ts#L11) means `require(./src/commands/foo/bar).run`. I think it is a bit difficult to understand for contributors. 
 Kind of +1. I like [@oclif/command](https://github.com/oclif/command)

**Comment by delvedor** [comment]
I'm +1, fastify-cli is growing and the current implementation does not scale well :)

**Comment by Eomm** [comment]
Great spot!
I'll give it a try also because it could be good for releasify aswell 👍

**Comment by xtx1130** [comment]
I have notice that `@oclif/command` needs >=node8. Whether maintainer should create a `next` branch to start refactor it.

**Comment by Eomm** [comment]
I have used our "default" stack (javascript + tap) to [build a cli](https://github.com/Eomm/kingdis) and I had some [troubles using tap](https://github.com/oclif/oclif/issues/280). 
I have done some workarounds to let it works) so I think it will be mandatory to switch to the suggested test suite.

The javascript snippets are missing too, so it took me to dig in the debugger sometimes (typescript seems a first-class citizen of the oclif community and the translation is not so much intuitive)

For sure the architecture of oclif can lead to reusable code and could let the community build stuff around fastify-cli to extend it

**Comment by StarpTech** [comment]
@eomm I don't understand your problems. Could you describe them one after another in detail? Check the linked issue I think I solve it.

**Comment by climba03003** [comment]
@xtx1130 
I see the PR #204 is pause for a few month, do you mine if I pick it up?

**Comment by climba03003** [comment]
I will be doing this when I have time.
