### ISSUE TITLE
Plugin need 3 arguments in function, also when returning a Promise

### ISSUE THREAD

**Issue by piranna** [fastify/fastify-cli#199]
## 🐛 Bug Report

When using a plugin that export a function that return a Promise, third argument is not needed, but `fastify-cli` refuse to run due to bad signature. It works if using an `async` function, but returning a Promise object is superfluous to define the function as `async`.

## Expected behavior

Being able to use a regular function (two arguments) when it returns a Promise, instead of needing to use an `async` function.

## Your Environment

- *node version*: 12.9.0
- *fastify version*: 2.7.1
- *os*: Linux Ubuntu 19.04

**Comment by mcollina** [comment]
Would you like to send a PR?

Il giorno sab 24 ago 2019 alle 15:04 Jesús Leganés-Combarro <
notifications@github.com> ha scritto:

**Comment by piranna** [comment]
> Would you like to send a PR?

I'm trying to do so, but seems to be a bit more complicated than expected. Tests ensure that when using a function it has three arguments, so the point is that it should be tested inside `fastify` that when it has two arguments, it's an `AsyncFunction` or a `Function` that returns a `Promise` object, instead of being checked here, but was not able to find the `register()` function inside `fastify` code. Do you think this is a good aproach? Where can I find the `register()` function source code?

**Comment by xtx1130** [comment]
@piranna  We can't judge a function's return value before we run it. And `register` is achieved by [`avvio`](https://github.com/mcollina/avvio)

**Comment by piranna** [comment]
> We can't judge a function's return value before we run it

I know, that's why I say this checking should be done there, not on `fastify-cli`.

**Comment by mcollina** [comment]
@piranna I think we can just remove the check here, the case on why this was added was solved long ago in https://github.com/mcollina/avvio/pull/72

**Comment by piranna** [comment]
If I understood It correctly, them yes, whe can remove this check.

**Comment by mcollina** [comment]
Exactly. Would you like to send a PR?

**Comment by piranna** [comment]
Fixed in #201... although seems the change was already done in `master` in the last days? :thinking:
