### ISSUE TITLE
Can not run fastify cli in watch mode with node inspector

### ISSUE THREAD

**Issue by pyxarez** [fastify/fastify-cli#200]
## 🐛 Bug Report

Cli is not working in --watch mode with node inspect on the board
It throws the following log: `Starting inspector on 127.0.0.1:9230 failed: address already in use`

## To Reproduce

Paste your code here:

```js
node --inspect-brk=9230 ./node_modules/.bin/fastify start --watch -l info -P app.js
```

## Expected behavior

It should work in --watch mode with node inspect on the board

## Your Environment

- *node version*: 10
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
This happens because we are forking the project: https://github.com/fastify/fastify-cli/blob/master/lib/watch/fork.js. We might want to do something about this, as it's a rather convenient feature.

Can you do the same with Nodemon for example? How do they implement/support it?

**Comment by pyxarez** [comment]
> Can you do the same with Nodemon for example? How do they implement/support it?
I don't fully understand the question
Yea, I can try to do the same with nodemon, but it requires [migrating](https://github.com/fastify/fastify-cli) from cli, making my own server.js and leads to loss of fastify-cli functionality like logging, default setup, etc.
It will look like this `nodemon --inspect=9230 server.js`

**Comment by mcollina** [comment]
You answered the question! `nodemon` implements it via a `--inspect` flag. Would you like to send a PR that adds that to fastify-cli as well?

**Comment by pyxarez** [comment]
Hmm, that's an interesting idea
Yeah, I can try to do that, but I'm new in fastify and I think it'll take some time
If you do not need super fast fix that's the task for me

**Comment by mcollina** [comment]
Go ahead!

**Comment by xtx1130** [comment]
I am sure `child_process.fork()` caused this, you need add options `{execArgv: []}` to `child_process.fork()`

**Comment by pyxarez** [comment]
@xtx1130 , I tried you suggestion and it's actually work!
But will this not lead to errors in the case when we really want to use execArgv?

**Comment by pyxarez** [comment]
I admit that that's an internal usage of `fork` and there is no case when someone would like to parametrise that part from outisde

**Comment by HighSoftWare96** [comment]
I'm going to make a PR of this if you want... I was able to manage that with `execArgv` parameter and adding a `debug` flag to the CLI.
![image](https://user-images.githubusercontent.com/22793967/63942214-8a2d9580-ca6d-11e9-9f39-b159893d8af9.png)
I'm trying now to use the `debug` flag also without watch mode.

**Comment by pyxarez** [comment]
@HighSoftWare96 yay! Great news:)
I don't have enough time for it anyway:)
Thank you

**Comment by xtx1130** [comment]
@pyxarez 
> But will this not lead to errors in the case when we really want to use execArgv?

I think it's better to move `execArgv` to `fork`'s `args`.

**Comment by HighSoftWare96** [comment]
I think this issue can be closed, don't you @pyxarez ? The initial behaviour can be solved now by using:
`fastify start --watch -l info -P app.js -d --debug-port=9230`

**Comment by pyxarez** [comment]
Yeah, sure
Thank you all for your help!

**Comment by almgwary** [comment]
Anyone know how to start fustily start on debugging mode? all above solutions not working with me. debug server is started but not attached to the running server.
