### ISSUE TITLE
FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: text/xml

### ISSUE THREAD

**Issue by MarkQH** [fastify/fastify-cli#206]
#### but when i use normal way to start a server as
 `const fastify = require('fastify')({
  logger: true
})
fastify.listen(3000)
`
#### I tried to use addContentTypeParser API. but no working

**Comment by RafaelGSS** [comment]
By default fastify only supports native `application/json` and `text/plain`. 

For you case, you can use `fastify-multipart`. See [ref](https://github.com/fastify/fastify/blob/master/docs/ContentTypeParser.md)

**Comment by vinnycosta1998** [comment]
I have the same problem, I already installed @fastify/multipart
