### ISSUE TITLE
Pass fastify server config params via fastify-cli

### ISSUE THREAD

**Issue by ivd** [fastify/fastify-cli#237]
How to pass fastify server config parameters via fastify cli? Any doc? Any suggestions?

**Comment by mcollina** [comment]
fastify-cli heavily relies on dotenv, check it out.

**Comment by ivd** [comment]
> fastify-cli heavily relies on dotenv, check it out.

Already checked, but still can't understand, how to pass, for example, parameter maxParamLength

**Comment by mcollina** [comment]
I don’t think that’s exposed. I think we need to provide some way to set those app-wide settings in a better way.

Have you got any ideas?

cc @Eomm @delvedor

**Comment by Eomm** [comment]
Is the `--options` flag providing this feature?

This example is in the readme: 
```
module.exports.options = {
  https: {
    key: 'key',
    cert: 'cert'
  }
}
```

and you should be able to add all the other fastify's options

**Comment by ivd** [comment]
> Is the `--options` flag providing this feature?
> 
> This example is in the readme:
> 
> ```
> module.exports.options = {
>   https: {
>     key: 'key',
>     cert: 'cert'
>   }
> }
> ```
> 
> and you should be able to add all the other fastify's options

Yes! This is what I was looking for! Somehow I`am not associated plugins options with server options. Thanks!
