### ISSUE TITLE
Custom plugin options

### ISSUE THREAD

**Issue by dnlup** [fastify/fastify-cli#240]
## 🚀 Feature Proposal
I think it could be useful to allow passing custom options to the plugin defined by the `app.js`. 
After reading the discussion at https://github.com/fastify/fastify-cli/issues/26 I would like to propose an alternative approach: exposing a `pluginOptions` property in `app.js`, the same way the custom options for Fastify are passed using the `options` property.

## Motivation

In some cases, you might need to define custom options for the `app.js` and you might want to be able to pass them directly through the `options` object or let `fastify-cli` inject them.

## Example

**app.js**
```js
module.exports = function (fastify, options, next) {
  ...
  next()
})

module.exports.options = {} // Cusom Fastify options

module.exports.pluginOptions = {} //Custom plugins options injected by fastify-cli
```

**Comment by Eomm** [comment]
Would `module.exports.pluginOptions = {}` be like `options` to create the Fastify instance, but injected via the cli? or who should be the reader of those options?

**Comment by dnlup** [comment]
> Would module.exports.pluginOptions = {} be like options to create the Fastify instance, but injected via the cli?

Yes, exactly, and contains specific options for the user app/plugin.

> who should be the reader of those options?

`fastify-cli` would read that object and pass it to the exported function, which in turn will consume it.

**app.js**
```js
module.exports = function (fastify, options, next) {
  console.log(options)
  next()
}

module.exports.pluginOptions = { active: true }
```
Then **fastify-cli** pass the specified options object to the function
```bash
$ fastify start app.js
{ active: true }
...
```

**Comment by Eomm** [comment]
I don't understand the benefit from the example above to this one:

```
const opts = { active: true }
module.exports = function (fastify, options, next) {
  console.log(opts)
  next()
}
```

It would be different instead of this usage:

```
# args after the double dash define the `options` input for the app.js
fastify start app.js -- --active=true
```

and app.js

```
module.exports = function (fastify, options, next) {
  console.log(options) // { active: true }
  next()
}
```

**Comment by dnlup** [comment]
Thank you for the feedback and for taking the time to respond to this :pray: 

> I don't understand the benefit from the example above to this one

I think that the main benefit is that when writing tests, you decouple app.js and its config. You also might use a separate module for loading configuration when running your app, like [env-schema](https://github.com/fastify/env-schema). In this way, you can export its result value to let the cli inject it if needed, and if you need to require just the function for testing purposes, you can discard those options.

> It would be different instead of this usage:
>``` # args after the double dash define the `options` input for the app.js```
> ```fastify start app.js -- --active=true```

That would be very useful indeed, is it supported? I honestly couldn't tell from the docs. I saw a PR open addressing this.

**Comment by mcollina** [comment]
I think adding support for passing in args would be nice.

**Comment by Eomm** [comment]
> I think that the main benefit is that when writing tests, you decouple app.js and its config

The target is clear, I'm not pro to the `module.exports.pluginOptions` because it is `app.js` that loads -using env-schema or other logic- the value of this option and so it is not decoupled: the test must know how `app.js` implemented the loading logic to change the `options`. So it should be a different actor that exposes those parameters. 
For this reason, I'm pro to a powerful `--` because the `app.js` receives the options without knowing how they are loaded at all.
(I say powerful because #208 simply decorate the `process.argv` and this could be optimized as you suggested, in order to be the input `options` 👍)

**Comment by dnlup** [comment]
> The target is clear, I'm not pro to the `module.exports.pluginOptions` because it is `app.js` that loads -using env-schema or other logic- the value of this option and so it is not decoupled: the test must know how `app.js` implemented the loading logic to change the `options`. So it should be a different actor that exposes those parameters.

I understand your point, and I agree that it should be a different actor. I thought that exposing the options this way would have been more in line with how fastify options are exposed, and I was wrong. Just to be clear, though, I wasn't suggesting using `pluginOptions` in tests, but the opposite. I would have used custom objects without knowing how `app.js` implemented the loading part. Anyway, I agree with you.

> For this reason, I'm pro to a powerful `--` because the `app.js` receives the options without knowing how they are loaded at all.

I like this approach too.

> (I say powerful because #208 simply decorate the `process.argv` and this could be optimized as you suggested, in order to be the input `options` )

Ok, so we can say that after #208 is merged, there is the groundwork for supporting this and that we would like to support it?

If the answer is yes, should I keep this issue open at this point, or should I open a new one?

Thank you again for the feedback.

**Comment by mcollina** [comment]
@dnlup if you want to take over that PR adding args, I think @davidmarkclements would be ok with it ;).

**Comment by dnlup** [comment]
@mcollina I will work on it then, thanks 🙂
