### ISSUE TITLE
NPM Audit Warning, Prototype Pollution of yargs-parser

### ISSUE THREAD

**Issue by mikeychowy** [fastify/fastify-cli#249]
## 🐛 Bug Report

Not actually a bug but an npm audit warning of prototype pollution. Don't know where to best put this so i just choose the bug report.

The warning was for fastify-cli 1.5.0's usage of yargs-parser 16.0.0. Apparently version 16 reintroduced proto pollution.

## To Reproduce

```command-line
npm init fastify
use version lens or any other version management plugins for IDEs and upgrade all the packages to latest (except tap, was worried it'll cause weird behavior for tests).
npm i
```

## Expected behavior

No prototype pollution warning. Don't know if it's that important since this is just the CLI but i'm kinda a stickler for these sorta things.

## Your Environment

- *node version*: 12.18.0
- *fastify version*: >=2.14.1
- *os*: Linux Ubuntu 16
- *fastify-cli version*: >=1.5.0

## Screenshots:
- [*the warning*](https://imgur.com/t3RfJCw)
- [*my package json*](https://imgur.com/vAMpOgL)

**Comment by mikeychowy** [comment]
after looking back at the npm audit screenshot, supposedly yargs-parser patched it 
```
>=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2
```
in those versions, now i'm wondering why npm still issued a warning for it....

**Comment by mcollina** [comment]
BTW this is not a vulnerability for this module, so don't worry about it. You have more critical vulns if you call this executable with untrusted user input.

It will be fixed in an upcoming release (already is on master)
