### ISSUE TITLE
Multiple decorators tests failure

### ISSUE THREAD

**Issue by alemagio** [fastify/fastify-cli#257]
## 🐛 Bug Report

Multiple plugins which create decorators are not registered correctly in test environment. 

## To Reproduce

See PR #256  .
Consider that the server is working perfectly, only tests fail.

## Expected behavior

Not sure if I am making something wrong or if the template generated by the CLI should be fixed.

## Your Environment

- *node version*: 12
- *os*: Linux
- created a project using `fastify generate`

**Comment by Eomm** [comment]
Solved in https://github.com/fastify/fastify-plugin/pull/95

Thks!
