### ISSUE TITLE
fastify routes command is broken with v3 applications

### ISSUE THREAD

**Issue by tchak** [fastify/fastify-cli#258]
## 🐛 Bug Report

`fastify routes` command is broken with v3 applications

## To Reproduce

```bash
fastify routes
```

## Stacktrace

```
TypeError: printRoutes(...).close is not a function
```

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
