### ISSUE TITLE
Add "--opts NAME=VALUE" in order to pass the parameters to plugin

### ISSUE THREAD

**Issue by allevo** [fastify/fastify-cli#26]
as titled

`fastify --opts VAR1=value1 --opts VAR2=value2 index.js`

`index.js`
```
module.exports = async function (fastify, opts) {
  fastify.register(require('fastify-env'), {
    schema: {
      type: 'object',
      required: ['VAR1'],
      properties: {
        VAR1: { type: 'string' },
        VAR2: { type: 'string', default: 'foo-bar' }
      }
    },
    env: false,
    data: [opts, process.env]
  })
    .after(err => {
      if (err) throw err
      console.log(fastify.config) // { VAR1: "value1", VAR2: "value2" }
    })
}
```

**Comment by mcollina** [comment]
I would prefer to load/parse a json/js file for this. It will also be simpler.

**Comment by allevo** [comment]
`fastify --config-file /path/to/js/or/json/file index.js` ?

**Comment by mcollina** [comment]
How about —config?

**Comment by allevo** [comment]
> How about —config?

ok.
But I'm not sure that a configuration file suite better that an command line argument.

I like a lot seeing the parameters on `ps aux` command on the server. What do you think?

**Comment by mcollina** [comment]
What others do? Doing these type of manipulations lead to complex code.

How about something like:

```
fastify index.js -- something else again
```

Which will invoke:

```js
fastify.register(require('index'), { args: 'something else again' })
```

Or some other combination to make this transparent without building a new option parsing tool.

**Comment by jimmiehansson** [comment]
Moving args into a separate construct seems rationale, that would benefit deprecation and legacy changes in the future
