### ISSUE TITLE
Support ESM modules

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-cli#267]
## 🚀 Feature Proposal

Support ESM module

## Motivation

In the node14 the ESM modules will be no longer experimental

## Example

```
// demo.mjs

import fs from 'fs'

export default function app (fastify, opts, next) {
  fastify.get('/', function (request, reply) {
    reply.send(fs.readFileSync('./package.json'))
  })

  next()
}
```
And then run it with `fastify start demo.mjs`

This feature should:

- load the arg file as ESM when the file ends with `mjs` or the `type` in the package.json is `module`

The watching feature should be updated accordingly.

To support node10, it will be needed a `--esm` `--no-esm` flag because it doesn't support the `type:module` loading as node>=12 does

**Comment by mcollina** [comment]
For whoever takes this, https://github.com/fastify/fastify-autoload has all the necessary examples on how to load _both_ cjs and mjs.

**Comment by danielglazer** [comment]
Hi, can I grab this? looking for my first contribution

**Comment by mcollina** [comment]
go for it!

**Comment by fox1t** [comment]
I would be happy to review that PR :)

**Comment by seriousme** [comment]
Just wondering: would it not be easier to just always  `import` as of Node 14.
`import` will happily import .js , .cjs and .mjs

E.g, in [util.js](https://github.com/fastify/fastify-cli/blob/master/util.js#L40) something like:
```javascript
const hasESM = process.version.split(/[v|\./]/)[1] >= 14
const serverPlugin = hasESM ? await import(resolvedModulePath) : require(resolvedModulePath)
```

This way you don't need all the extra logic present in  https://github.com/fastify/fastify-autoload 
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import 'import()'  does not need the URL format so that would alleviate the need of importing the URL module.

Did I miss something ?
I plan to add a similar trick to fastify-openapi-glue, so any knowledge gained here would help me as well ;-)

Kind regards,
Hans

**Comment by seriousme** [comment]
It turns out that `import` returns an object containing the export so to get it to work it needs to be something like:
```javascript
const hasESM = process.version.split(/[v|\./]/)[1] >= 14
const serverPlugin = hasESM ? (await import(resolvedModulePath)).default : require(resolvedModulePath)
```
Kind regards,
Hans

**Comment by mcollina** [comment]
It likely would!

**Comment by fox1t** [comment]
I am confused: I think we also need top-level await to support what you suggest @seriousme, aren't we?

**Comment by fox1t** [comment]
I also suggest checking all of the `import()` cases in this playground: https://github.com/fox1t/modules-playground/tree/master/modules.
As you can see, they are not all identical, and, in my experience, the dynamic `import()` is the one that more often has quirks because it depends upon the module context where it is used.

**Comment by seriousme** [comment]
> I am confused: I think we also need top-level await to support what you suggest @seriousme, aren't we?

Nope, you only need an `async function` to be able to use `await`. Hence Async/Await ;-)
An async function always returns a promise (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

so this works, even in Node 10.21.0:

```javascript
async function double(x) {
    return x * 2;
}

async function quad(x) {
    const y = await double(x)
    const q = await double(y)
    return q
}

quad(3).then(y => console.log(y))
```

**Comment by seriousme** [comment]
> I also suggest checking all of the `import()` cases in this playground: https://github.com/fox1t/modules-playground/tree/master/modules.
> As you can see, they are not all identical, and, in my experience, the dynamic `import()` is the one that more often has quirks because it depends upon the module context where it is used.

It looks like you put quite some effort in this!
I glanced at your examples and I saw lots of named imports ;-)

As you can see my example only aims at default imports as named imports are rather unusable in this context imho.
Do you foresee any issue with just the default imports ? 

Kind regards,
Hans

**Comment by seriousme** [comment]
I have been tinkering a bit with the code:

I changed two lines:
`function requireServerPluginFromPath (modulePath)` to `async function requireServerPluginFromPath (modulePath)`
in Util.js
and 
`file = requireServerPluginFromPath(opts._[0])` to `file = await requireServerPluginFromPath(opts._[0])`
in `print-routes.js`

This should give imho identical results as before however it causes many tests to break.
E.g. `node test/start.test.js` results in:
```
# test count(32) != plan(12)
# failed 23 of 32 tests
# skip: 1
# time=1651.306ms
```
Both on Node 10 and on Node 14.

Weird thing here is that one of the failed tests now reports a promise instead of a filename in its Error object while the promise should already have been resolved by the `await` and the code that produces the filename has not been touched!
```
ok 9 - should start fastify at given socket path # time=76.975ms

# Subtest: should error with a good timeout value
    1..1
    not ok 1 - should be equal
      ---
      compare: ===
      at:
        line: 250
        column: 7
        file: test/start.test.js
        type: Test
        function: test
      stack: |
        Test.test (test/start.test.js:250:7)
      source: >2
          } catch (err) {
            t.equal(err.message, `ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: ${path.join(__dirname, 'data', 'timeout-plugin.js')}`)
        ------^
          }
        })
      diff: >
        --- expected
      
        +++ actual
      
        @@ -1,1 +1,1 @@
      
        -ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /home/mydir/github/fastify-cli/test/data/timeout-plugin.js
      
        +ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: [object Promise]
      ...
    
    # failed 1 test
```

Any ideas ? Is this a problem with Tap ?

Kind regards,
Hans

**Comment by mcollina** [comment]
There are more `await` to add, and it's likely not a 2-line change :). Keep tinkering!

**Comment by seriousme** [comment]
I  know its not a 2 line change, but this was the bare minimum of changes that already caused it to fail ;-)

Weird thing is that `node test/print-routes.test.js` runs all 7 tests without issues. That same test suite  fails all 7 tests when I mess with the `require` by using `const serverPlugin = require(resolvedModulePath+"blah")` so the async require works in this test !

Running npm test results in only one failing test suite: `start.test.js`
And in that test its a mixed bag as well, see the next summary
```
ok 1 - should start the server # time=421.746ms
ok 2 - should start the server with a typescript compiled module # time=40.658ms
ok 3 - should start the server with pretty output # time=59.485ms
ok 4 - should start fastify with custom options # time=13.887ms
ok 5 - should start fastify with custom plugin options # time=35.594ms
not ok 6 - should start fastify with custom options with a typescript compiled plugin # time=192.077ms
ok 7 - should start fastify with custom plugin options with a typescript compiled plugin # time=83.465ms
ok 8 - should start the server at the given prefix # time=75.757ms
ok 9 - should start fastify at given socket path # time=44.277ms
not ok 10 - should error with a good timeout value # time=182.356ms
not ok 11 - should warn on file not found # time=22.84ms
not ok 12 - child test left in queue: t.test should throw on package not found
not ok 13 - child test left in queue: t.test should throw on parsing error
not ok 14 - child test left in queue: t.test should start the server with an async/await plugin
not ok 15 - child test left in queue: t.test should exit without error on help
not ok 16 - child test left in queue: t.test should throw the right error on require file
not ok 17 - child test left in queue: t.test should respond 413 - Payload too large
not ok 18 - child test left in queue: t.test should start the server (using env var)
not ok 19 - child test left in queue: t.test should start the server (using PORT-env var)
not ok 20 - child test left in queue: t.test should start the server (using FASTIFY_PORT-env preceding PORT-env var)
not ok 21 - child test left in queue: t.test should start the server (using -p preceding FASTIFY_PORT-env var)
not ok 22 - child test left in queue: t.test should start the server at the given prefix (using env var)
not ok 23 - child test left in queue: t.test should start the server at the given prefix (using env var read from dotenv)
not ok 24 - child test left in queue: t.test should start the server listening on 0.0.0.0 when runing in docker
ok 25 - should start the server with watch options that the child process restart when directory changed # SKIP
not ok 26 - child test left in queue: t.test crash on unhandled rejection
not ok 27 - child test left in queue: t.test should start the server with inspect options and the defalut port is 9320
not ok 28 - child test left in queue: t.test should start the server with inspect options and use the exactly port
not ok 29 - child test left in queue: t.test boolean env are not overridden if no arguments are passed
not ok 30 - child test left in queue: t.test should support custom logger configuration
not ok 31 - child test left in queue: t.test should throw on logger configuration module not found
not ok 32 - child test left in queue: t.test should throw on async plugin with one argument
```

My current hypothesis is that its a flaw in the test suite that is triggered by something like a change in timing and not so much in my 2 line code change 
The positive thing is that the test consistently fail, its not fully random.

So if anyone has any ideas or if you want me to add the output of the test run, please shout !

Kind regards,
Hans
ps. do you still want to keep the "good first issue" label ? ;-)

**Comment by seriousme** [comment]
Decided to try to skip the failing tests one by one to see what happens:

ok 6 - should start fastify with custom options with a typescript compiled plugin # SKIP
ok 10 - should error with a good timeout value # SKIP
ok 11 - should warn on file not found # SKIP
ok 12 - should throw on package not found # SKIP
ok 13 - should throw on parsing error # SKIP
ok 16 - should throw the right error on require file # SKIP
ok 25 - should start the server with watch options that the child process restart when directory changed # SKIP
ok 29 - boolean env are not overridden if no arguments are passed # SKIP
ok 30 - should support custom logger configuration # SKIP
ok 31 - should throw on logger configuration module not found # SKIP
ok 32 - should throw on async plugin with one argument # SKIP

Thats 11 tests that need to be skipped to get the other 21 to complete.
Most of them seem related to catching errors and timeouts.

**Comment by seriousme** [comment]
Well that was fun...

Turns out that I got fooled by Github Search :-(

Github search only mentioned `lib/print-routes.js` as caller of `requireServerPluginFromPath` but as you all probably already knew the same function is used directly from `start.js`

Putting in an await there as well magically solves most of the issues:
```
 FAIL  test/start.test.js 1 failed 1 skip of 77 5s
 ✖ should throw on async plugin with one argument
 ~ should start the server with watch options that the child process restart when directory changed
```
Still surprised why the other tests worked without the await in `start.js`, but I will leave that to rest.

To be continued..

**Comment by seriousme** [comment]
FYI it needs to be `import(url.pathToFileURL(resolvedModulePath).href` instead of just `import(resolvedModulePath)` because on Windows a path can be 'D:/blah/blah' which import() sees as URL protocol D

**Comment by fox1t** [comment]
> FYI it needs to be `import(url.pathToFileURL(resolvedModulePath).href` instead of just `import(resolvedModulePath)` because on Windows a path can be 'D:/blah/blah' which import() sees as URL protocol D

Oh, here we are again! Our old friend @mcollina XD

**Comment by kibertoad** [comment]
Since the linked PR is merged, can this be closed?

**Comment by minemax-ua** [comment]
So, is there a way to make fastify-cli *generate* code with esm modules (instead of rather outdated 'require')?

**Comment by ram-you** [comment]
@minemax-ua 
I created a new issue https://github.com/fastify/fastify-cli/issues/539
