### ISSUE TITLE
Generate plugin command

### ISSUE THREAD

**Issue by alemagio** [fastify/fastify-cli#268]
## 🚀 Feature Proposal

I created [create-fastify-plugin](https://github.com/alemagio/create-fastify-plugin)

I needed a simple tool to create a boilerplate when I wanted to publish my own plugin.
It should be easy to integrate it in fastify-cli.
I would love to do it.

But, off course, if you think this is not out of the project's scope.

**Comment by mcollina** [comment]
+1 to integrate it!

**Comment by alemagio** [comment]
PR ready for review.
