### ISSUE TITLE
fastify eject

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-cli#277]
## 🚀 Feature Proposal

If somebody is using `fastify start`, they might also want to eject and have a `server.js` file that they can use to launch their application on their own, removing the dependency on fastify-cli.
Essentially automating https://github.com/fastify/fastify-cli#migrating-out-of-fastify-cli-start.

**Comment by yigitkurtcu** [comment]
I want to look at this. Will this feature be provided by adding an option to the **fastify generate** command?

**Comment by mcollina** [comment]
I would prefer this to be a new command. Folks might change their mind.

**Comment by joobisb** [comment]
@mcollina I would like to raise a PR on this.
