### ISSUE TITLE
Typescript handling broken in 2.4

### ISSUE THREAD

**Issue by danez** [fastify/fastify-cli#279]
## 💥 Regression Report

#276 (2.4.0) screwed up our whole typescript dev workflow. We had it working perfectly fine (including watching) before with simply doing
```
ts-node ./node_modules/.bin/fastify start -w -l info -P -p 3001 src/index.ts
```
Nothing else was required to get it working, no code changes etc. (Imho this would also be an easier solution than all the code changes in #276)

In the new version fastify-cli now first errors with 
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:122:11)
    at resolve (path.js:980:7)
    at watchMain (/Users/tschinde/Documents/rg/tech-dept-app/api/node_modules/fastify-cli/lib/watch/tsc-watcher.js:50:24)
```
because we do not specify an `outDir` directly in the main typescript config, but rather in the some inherited config. Even after changing this and defining an `outDir` and `rootDir` the emitting of files is not working correctly. I have my source in `src/` and the code emitted is going into `lib/src/` but that is not where it should go, it should just go into `lib/`. So the app crashes because it cannot find files.

my tsconfig (with outDir and rootDir specified to fix above, with ts-node only `rootDir: "./"` was set which is also needed for the typescript tests) is:
```
{
    "include": [
      "src"
    ],
    "extends": "../tsconfig.json",
    "compilerOptions": {
      "outDir": "lib",
      "rootDir": "src"
    }
  }
```

`../tsconfig.json` is:
```
{
  "exclude": ["node_modules", "__tests__", "dist", "lib"],
  "compilerOptions": {
    "lib": ["es2019"],
    "target": "es2019",
    "module": "commonjs",
    "rootDir": ".",
    "outDir": "lib",
    "strict": true,
    "allowJs": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "declaration": false,
    "sourceMap": false,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "isolatedModules": true
  }
}
```

For now I reverted and will stay on latest 2.3.x

## Last working version

Worked up to version: 2.3.x

Stopped working in version: 2.4.0

## Your Environment

- *node version*: 12
- *fastify version*: 3.6.0
- *os*: Mac
- *ts*: 3.9.7

**Comment by mcollina** [comment]
I'm sorry to ear this :(, this was definitely not intended. I would recommend you to lock the dependency to v2.3 while we fix this up.

@alemagio @fastify/typescript we might have to revert https://github.com/fastify/fastify-cli/pull/276

**Comment by alemagio** [comment]
Sure, sorry for this.
I'll fix it as soon as possible.

**Comment by danez** [comment]
No worries. To give more context we have two ts configs one for production build `tsconfig.build.json` and one for dev and tests `tsconfig.json`. Our product is separated into an API app (fastify) and a web/frontend app. This is why we share some parts of the tsconfigs in the repo root
```
root/->
       -> api/
                 -> tsconfig.json
                 -> tsconfig.build.json
        -> web/
                 -> tsconfig.json
                 -> tsconfig.build.json
         -> tsconfig.json
         -> tsconfig.build.json
```

`(api/web)/tsconfig.json` on purpose defines `rootDir` as './' because jest also needs to compile the tests which are not in source, and ts-node does not care because it only compiles files that are actually required/imported. Both jest (babel) and ts-node do not emit files so we don't have to care for an `outDir`, although it is still set to `lib` in the root config. I cannot remember but eslint  and the ts parser might also use this file.
```
{
    "include": [
      "src"
    ],
    "extends": "../tsconfig.json",
    "compilerOptions": {
      "outDir": "./"
    }
  }
```

`(api/web)/tsconfig.build.json`
```
{
  "include": ["src"],
  "extends": "../tsconfig.build.json",
  "compilerOptions": {
    "outDir": "lib",
    "rootDir": "src",
    "noImplicitAny": false
  }
}
```

`/tsconfig.json` tests are not excluded in contrast to the build config.
```
{
  "exclude": ["node_modules", "dist", "lib"],
  "compilerOptions": {
    "lib": ["es2019"],
    "target": "es2019",
    "module": "commonjs",
    "rootDir": ".",
    "outDir": "lib",
    "strict": true,
    "allowJs": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "declaration": false,
    "sourceMap": false,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "isolatedModules": true
  }
}

```

`/tsconfig.build.json`
```
{
  "exclude": [
    "node_modules",
    "dist",
    "lib",
    "__tests__",
    "**/*.test*",
    "**/*.spec*"
  ],
  "compilerOptions": {
    "lib": ["es2019"],
    "target": "es2019",
    "module": "commonjs",
    "rootDir": ".",
    "outDir": "lib",
    "strict": true,
    "allowJs": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "declaration": false,
    "sourceMap": false,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "isolatedModules": true
  }
}
```

**Comment by alemagio** [comment]
Thanks for all the info.
This helps a lot :star_struck: 
The idea behind last changes was basically to use the typescript watcher in place of `ts-node`, but, for what I've seen here I might have not considered enough scenarios.
I'll take all your report and try to make it better :+1: with the help of the community.

**Comment by alemagio** [comment]
I also noticed that I added a new option to specify the `ts-config` file to use when running `start` but it is not documented.
Just another thing to do saturday morning i guess :sweat_smile:

**Comment by fox1t** [comment]
Hi @danez, your is one of the most complex project structures I've ever seen, and it would be nice to use it as a test bench. Would you mind providing a repository here on GitHub with the same structure, scripts, and dependencies, but without your app code? :)

**Comment by fox1t** [comment]
@alemagio we can see if it is possible to have a consistent number of cases handled by the "manual ts watcher." If not, we can leave that part to final users!

**Comment by alemagio** [comment]
@fox1t 
Makes sense.

**Comment by mcollina** [comment]
any progress with this? Should we do a revert? @fox1t @alemagio?

**Comment by alemagio** [comment]
@mcollina 
I'm working on it right now.
I solved one of the issue (the system did not include parent configurations).
IMHO the problem is not easy to solve as I thought in the first place, so, maybe, we can consider reverting this and, eventually, I'll keep working on it and I might propose a new solution in the future.
I'm working on this in my free time so I can't assure a solution briefly :sweat_smile:.
What do you think?

**Comment by mcollina** [comment]
I'll ship a revert in the morning.

**Comment by danez** [comment]
Here is the example repo. https://github.com/danez/ts-example-app
Thanks for all your hard work. 💚

**Comment by alemagio** [comment]
@danez 
Thanks a lot for the repo, I cloned it and solved another issue thanks to it.

**Comment by fox1t** [comment]
@danez, thanks for your repo.
@mcollina revert would be ok for the moment. We can use the provided repository to iterate over this. As I said, it is a complext project configuration and it will help us understand if this is even achievable at the cli leverl or is something to leave in userland. At the moment, I think that we can standardize/suggest `ts-node ./node_modules/.bin/fastify start -w -l info -P -p 3001 src/index.ts`.

**Comment by mcollina** [comment]
Reverted in v2.5.0
