### ISSUE TITLE
could  fastify cli generate a new route with a independent schema file，handler etc?

### ISSUE THREAD

**Issue by radiorz** [fastify/fastify-cli#301]
## 🚀 Feature Proposal

if i want to create new route, i should create route,schema and handler etc by myself,could fastify-cli do this automatically ?

## Example
![image](https://user-images.githubusercontent.com/24271959/102580602-d5275c80-4139-11eb-8734-048e1276c735.png)

**Comment by mcollina** [comment]
I would recommend against that folder structure. route, schema and handler changes together, so they should stay together.

**Comment by radiorz** [comment]
thanks for your recommend @mcollina . if possible please tell me what is a best folder structure should be.

**Comment by mcollina** [comment]
I put 1 route per file, including the code for the controller and the schema.
