### ISSUE TITLE
Typescript template does not work with start command

### ISSUE THREAD

**Issue by alemagio** [fastify/fastify-cli#303]
## 🐛 Bug Report

Simply running `npm run dev` of `npm run start` in a clean typescript template does not work:

![image](https://user-images.githubusercontent.com/21338507/102900441-8d237500-446c-11eb-9cf6-e58f6c14a982.png)

Changing the import to `import { join } from "path"` fixes the issue but another one comes out:

![image](https://user-images.githubusercontent.com/21338507/102900597-ceb42000-446c-11eb-8465-b66f3acdee14.png)

## Your Environment

- *node version*: 12 and 14
- *fastify version*: >= 3
- *os*: Linux

Adding `esModuleInterop` to tsconfig.json fixes both.

**Comment by kibertoad** [comment]
@alemagio Could you please provide full reproduction? When I try to compile locally after changing import and `path.join` to `join`, it just compiles fine.

**Comment by shermanlai** [comment]
I ran into the same issue with a fresh TS install. 

Node 14
WSL Ubuntu.
Fastify CLI 2.7.0

```
fastify generate --lang=ts map2
cd map2
npm install
npm run start
```

I get the same `Error: plugin must be a function or a promise` shown above.

**Comment by alemagio** [comment]
@kibertoad 
I think I found something in fastify-autoload.
I just opened a PR, hope is fine :smile: .

**Comment by zekth** [comment]
Is this still happening since the merge in auto-load?

**Comment by alemagio** [comment]
Hi @zekth 
I just tried and seems to work now.
