### ISSUE TITLE
No server.ts in templates/eject

### ISSUE THREAD

**Issue by mnffaisy1** [fastify/fastify-cli#307]
## 🚀 Feature Proposal

hello guys
there should be a server.ts in templates/eject/

**Comment by mcollina** [comment]
We should add an `eject-ts` command. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mnffaisy1** [comment]
Yes i'd... i'm a newbie in javascript but looking forward to contribute to fastify project.  i don't know node-tap but i'll try my best.

**Comment by mnffaisy1** [comment]
can anyone post here a server.js template?

**Comment by mnffaisy1** [comment]
please make sure **_server.ts_** is perfect...
