### ISSUE TITLE
Listening on a specific host crashes at startup

### ISSUE THREAD

**Issue by reilem** [fastify/fastify-cli#310]
## 🐛 Bug Report

When specifying a host IP address on  `listen` causes crash on startup

## To Reproduce

(Here 127.0.0.1 is used, but I also tested: 192.168.x.x (my local IP) and  0.0.0.0 none of them worked)

```js
export default async function (app, opts, next) {
  app.listen(3000, '127.0.0.1', (err, address) => {
    if (err) {
      app.log.error(err);
      process.exit(1);
    }
  });
}
```

Resulting crash & error:

```bash
$ fastify start -l info ./build/index.js
{"level":30,"time":---,"pid":---,"hostname":"---","msg":"Server listening at http://127.0.0.1:3000"}
Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1384:11)
    at /Users/Reinert/Documents/Coding/Ventory/GraphQL.nosync/node_modules/fastify/lib/server.js:101:18
    at new Promise (<anonymous>)
    at /Users/Reinert/Documents/Coding/Ventory/GraphQL.nosync/node_modules/fastify/lib/server.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runFastify (/Users/Reinert/Documents/Coding/Ventory/GraphQL.nosync/node_modules/fastify-cli/start.js:136:5)
error Command failed with exit code 1.
```

## Expected behavior

I expect it not to crash and host on the specified IP. I need this to test the backend using mobile devices.

## Your Environment

- *node version*: 12
- *fastify version*: 3.0.3
- *os*: Mac

**Comment by reilem** [comment]
I am able to get it working using the `-a` flag, but still it would be nice if this also worked in code.

**Comment by mcollina** [comment]
That's totally expected. If you'd like to manually listen, you should use `fastify eject` to create a `server.js` file.

**Comment by MFinn87** [comment]
@mcollina Can we open this back up, please? This is a genuine issue, and the server should not be attempting to listen more than once, on the same host/port. Thank you kindly.

**Comment by climba03003** [comment]
> 
> 
> Hey @mcollina,
> 
> This is a genuine issue, and the server should not be attempting to listen more than once, on the same host/port.
> 
> Can we open this back up, please?
> Or at least maybe an explanation as to why duplicate port listening is expected?
> Or why host cannot be set in code without error.
> 
> Thank you kindly,
> MFinn87

`fastify start` treat the file as plugin, so you should not `listen` your instance inside the file. If you need to change those options, pass it through the option of `fastify start`.
e.g. `fastify start plugin.js --address 127.0.0.1 --port 3000`

**Comment by MFinn87** [comment]
Thank you for the response @climba03003 . Your solution with `--address` and `--port` flags work without calling `fastify.listen`.
