### ISSUE TITLE
Add fastify-sensible to the project template

### ISSUE THREAD

**Issue by alemagio** [fastify/fastify-cli#312]
As titled, I believe it might be useful to add `fastify-sensible` to the project template.
I know it would be the first plugin added to the template (apart from `fastify-autoload` and `fastify-plugin` which are kinda unique as plugins) but it looks very generic so in my opinion it would not make the template too opinionated.
What do you think?

**Comment by mcollina** [comment]
unfortunately fastify-sensible add a custom error handler that essentially cripples it for greater reuse. Maybe we could just remove it from there, so we can add it to this module.

I would add fastify-sensible inside the `plugins` folder.

**Comment by alemagio** [comment]
Yes I meant inside the `plugins` folder basically.

> unfortunately fastify-sensible add a custom error handler that essentially cripples it for greater reuse

You mean [this](https://github.com/fastify/fastify-sensible/blob/b08cbec7f37c2d834c91c0acdfe5b1ef5c3339c6/index.js#L46)?

**Comment by mcollina** [comment]
I'm happy to add fastify-sensible here with the caveat that errorHandler option is set to false.

**Comment by alemagio** [comment]
> I'm happy to add fastify-sensible here with the caveat that errorHandler option is set to false.

Perfect, gonna work on that this weekend hopefully.

**Comment by anthonyringoet** [comment]
Think this can be closed as PR https://github.com/fastify/fastify-cli/pull/313 was merged.
