### ISSUE TITLE
Load a file before everything else

### ISSUE THREAD

**Issue by delvedor** [fastify/fastify-cli#314]
## 🚀 Feature Proposal

Offer a way to run a specific file before everything else, à la `node -r foo index.js`

## Motivation

Most APM vendors needs to be posed before anything else, which is currently not possible with the CLI.

## Example

```
fastify start -r apm.js app.js
```

**Comment by mcollina** [comment]
sure!

**Comment by anthonyringoet** [comment]
Merged to master so can be closed afaik.

**Comment by mhamann** [comment]
@mcollina any chance we can get a release with this in it?
