### ISSUE TITLE
Cannot modify logger via server config

### ISSUE THREAD

**Issue by s1eeper888** [fastify/fastify-cli#315]
## 🐛 Bug Report

When initializing server config and modifying a property, such as: timestamp does not work.

## To Reproduce

```
// app.js
async function app(fastify, opts) {

  // Global plugins
  fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: Object.assign({}, opts),
  });

  // Service route plugins
  fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: Object.assign({}, opts),
    maxDepth: 2,
  });

  fastify.ready(err => {
    if (err) {
      fastify.log.fatal(err);
      process.exit(1);
    }
  });
}

app.options = {
  logger: {
    timestamp: () => `,"time":"${new Date(Date.now()).toISOString()}"`,
  }
};

module.exports = app;
```

```
// package.json
"scripts": {
  "dev": "fastify start -w -l info -o app.js -- --dev",
}
```

## Expected behavior
current:
```
{"level":50,"time":1613478724788,"pid":xxx,"hostname":"xxx","msg":"xxx"}
```
expected:
```
{"level":50,"time":2021-02-16T12:43:04.850Z,"pid":xxx,"hostname":"xxx","msg":"xxx"}
```
I expect stdout timestamp to be using ISO format versus Epoch format.

## Your Environment

- Node 14.15.3
- *fastify version*: 3.0.0
- *fastify cli version*: 2.6.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Iamshankhadeep** [comment]
@mcollina I want to take on this issue. But need a little bit of help. I go through the codebase but I am not sure how `logger` gets applied.

**Comment by mcollina** [comment]
here: https://github.com/fastify/fastify-cli/blob/ca72e80c2efe6e1c0fd172176b51fe4b8546c304/start.js#L103-L135

**Comment by Iamshankhadeep** [comment]
hey @mcollina I tested tried to reproduce the issue and it does log the expected value. I guess it's been fixed in latest version.
```bash
node cli.js start -w -l info -o ./test-app/app.js -- --dev
{"level":30,"time":"2021-05-05T16:51:23.999Z","pid":98489,"hostname":"xxx","msg":"Server listening at http://127.0.0.1:3000"}
```
