### ISSUE TITLE
Add graceful shutdown

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-cli#317]
## 🚀 Feature Proposal

Most users would expect to have a graceful shutdown sequence, where all the current requests are completed before exiting the process.

[close-with-grace](http://npm.im/close-with-grace) implement such functionality, so I propose we use it inside `fastify start` and inside the server generated by `fastify eject`.

**Comment by StarpTech** [comment]
It would be great to make it part of [`fastify.close`](https://github.com/fastify/fastify/blob/master/docs/Server.md#close) so plugin maintainers can ensure that their resources are cleaned gracefully.

**Comment by mcollina** [comment]
I think the idea would be:

```js
const closeWithGrace = require('close-with-grace')

closeWithGrace({ delay: 500 }, async function ({ signal, err, manual }) {
  if (err) {
    fastify.log.error(err)
  }
  await fastify.close()
})
```

**Comment by StarpTech** [comment]
That's great but every new project has to respect that. The plugin so soo small but would have a huge impact.

**Comment by mcollina** [comment]
> That's great but every new project has to respect that. 

I know. Unfortunately adding global state would make it harder to reuse and test. As an example, `tap` adds `uncaughtException` and `unhandledRejection` handlers to catch errors that happens inside the tests. Other test frameworks, libraries and other modules adds those.

**Comment by StarpTech** [comment]
Good points. I agree that can be tricky.

**Comment by inigo-garcia** [comment]
I started to integrate this feature and after running some tests, I think we may need to remove the listeners once the server gets closed. The library implements a method called `closeWithGrace.uninstall()`. What do you think?
