### ISSUE TITLE
Broken upstream dependency "blessed-contrib" blocking installation

### ISSUE THREAD

**Issue by prescience-data** [fastify/fastify-cli#322]
## 🐛 Bug Report

Broken upstream dependency `blessed-contrib` > `marked-terminal` + `marked` from a recent `package.json` commit in `marked-terminal`.

```error
[ERROR] > fastify-cli > blessed-contrib: marked-terminal@4.1.1 requires a peer of marked@^1.0.0 || ^2.0.0 but version 0.7.0 was installed.
```

### Broken `blessed-contrib` package.json:
https://github.com/yaronn/blessed-contrib/blob/master/package.json#L35

### offending `marked-terminal` upstream commit:
https://github.com/mikaelbr/marked-terminal/commit/abba40b6d0150c591ca92a6ec70c5c0103c41a4a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Also referenced here: https://github.com/yaronn/blessed-contrib/issues/209

## To Reproduce

```shell
$ pnpm install fastify-cli
```
 
## Your Environment

- *node version*: 14
- *fastify version*: latest
- *using pnpm*

**Comment by mcollina** [comment]
Does this work with npm? That seems a valid package.json to me. Maybe this should be supported in pnpm.

**Comment by prescience-data** [comment]
The `marked-terminal` requires a peer dependency of `"marked": "^1.x.x || ^2.x.x"`, whereas `blessed-contrib` is only installing `"marked": "^0.x.x"`

![image](https://user-images.githubusercontent.com/65471523/109862621-c2421400-7cb4-11eb-97b6-4468c8fe0eb4.png)

Not a problem if not using `strict-peer-dependencies` but for projects that require this (for whatever reason) it makes it `FAIL` instead of `WARN` which blocks installation of `fastify-cli`.

![image](https://user-images.githubusercontent.com/65471523/109863495-cf133780-7cb5-11eb-8223-501ed7ae0eb5.png)


It's absolutely a `blessed-contrib` issue _(and in regards to the strict mode, the client project being worked on)_ rather than a `fastify-cli` issue, but not sure how active that repo is by comparison. 😕

**Comment by prescience-data** [comment]
🥳 lol got them to disable the `strict-peer-dependencies` flag in the project, so closing for now.
