### ISSUE TITLE
Update README.md with the latest code for migrating out of the cli start from the templates

### ISSUE THREAD

**Issue by omardoma** [fastify/fastify-cli#338]
## 🐛 Bug Report

The README.md [Migrating out of fastify-cli start](https://github.com/fastify/fastify-cli#migrating-out-of-fastify-cli-start) section contains out-of-date code missing graceful shutdown.

## To Reproduce

Open the README.md [Migrating out of fastify-cli start](https://github.com/fastify/fastify-cli#migrating-out-of-fastify-cli-start) section and compare it against the [eject](https://github.com/fastify/fastify-cli/blob/master/templates/eject/server.js) template.

## Expected behavior

Both should be in sync.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by DennisBoanini** [comment]
@mcollina Can I work on this issue?

**Comment by mcollina** [comment]
go for it!

**Comment by omardoma** [comment]
@DennisBoanini @mcollina I have just raised a [PR](https://github.com/fastify/fastify-cli/pull/347) for it.

**Comment by mcollina** [comment]
Thanks!
