### ISSUE TITLE
fastify -r does not behave like node -r

### ISSUE THREAD

**Issue by madflow** [fastify/fastify-cli#357]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.15.1

### Node.js version

16.0.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Big Sur

### Description

fastify -r does not behave like node -r

Maybe a feature - not a bug :S.

### Steps to Reproduce

When I start an application with fastify cli like so:

`fastify start -r '@app/config/env' -w -l info -P dist/app.js`

`
[App] Error: Cannot find module '/'
...
[App]   code: 'MODULE_NOT_FOUND',
...
`

`@app/config/env` holds the `PORT` and is required as dependency in my package.json. It is a package in a mono-repo managed with yarn workspaces.

When I do the same with an ejected server and Node.JS

```
➜  server git:(fastify) ✗ node server.js
{... Server listening at http://127.0.0.1:3000"}

thing ➜ server git:(fastify) ✗ node -r '@app/config/env' server.js
{... Server listening at http://127.0.0.1:5000"}
```

### Expected Behavior

I would expect `fastify -r ` to behave like `node -r`.

**Comment by mcollina** [comment]
You are right! Would you like to send a PR?

**Comment by madflow** [comment]
> You are right! Would you like to send a PR?

I can surely give it a shot!
