### ISSUE TITLE
Some times typescript doesn't generate js code in dev so you have to manually delete dist folder for it to pick up

### ISSUE THREAD

**Issue by veritem** [fastify/fastify-cli#361]
Hello, on the dev server for the typescript template it would be great if you could an option to remove and regenerate the dist folder every time the server starts to reduce bugs that normally happens when typescript doesn't generate some piece of code in development.

or if there is any other way to resolve the issue,

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by alemagio** [comment]
I think you can add `tsc --build --clean` as the first command in your `dev` script (if you are using the one generated by the CLI).
It should cleanup all the generated typescript projects.
[doc](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
