### ISSUE TITLE
Add default readme for generated project

### ISSUE THREAD

**Issue by veritem** [fastify/fastify-cli#362]
When new project is generated it would be great if you could add a default readme that it was generated by fatisfy-cli

**Comment by khattakdev** [comment]
I'm writing code for this issue by adding a `README.md` file in `templates/app` and `templates/app-ts`. After adding the `readme` when I run the tests, 2 of them fail. 
![image](https://user-images.githubusercontent.com/37709578/122676703-9a8da200-d1f8-11eb-91a1-82ba744901ca.png)

I tried going step by step (debugging) but couldn't find the solution. Any help will be appreciated.

**Comment by mcollina** [comment]
there is likely something that would need to be adjusted in the test. It seems the new files are not inside the `expected` map.

**Comment by khattakdev** [comment]
> there is likely something that would need to be adjusted in the test. It seems the new files are not inside the `expected` map.

I don't think so that's the case, Here are the `expected` key values
![image](https://user-images.githubusercontent.com/37709578/122737027-125fd900-d29a-11eb-81b0-901b25297431.png)
