### ISSUE TITLE
`fastify start` command is throwing `missing file parameter` error on Windows

### ISSUE THREAD

**Issue by UmarGhouse** [fastify/fastify-cli#367]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

^3.15.1

### Node.js version

15.14.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

2004

### Description

I just joined a project that uses fastify as their backend framework of choice and we have the following npm script to launch the server during development:

```
fastify start -w server/fastify.js --options --ignore-watch='out.csv node_modules ui .nyc_output' | pino-pretty
```

I managed to run this on Windows Sub-system for Linux (WSL), but not on the native powershell. Whenever I try to run this on powershell I get the following error:

```
Missing the required file parameter

Usage: fastify start [opts] <file> [--] [<plugin-options>]
```

But from what I can tell, we are specifying the file parameter as `server/fastify.js` in the script. 

Any idea why this fails on Windows, but works fine on WSL? Both my Windows and WSL have the same versions of Node and npm and are running on the same laptop.

It also works fine on my colleagues Macs as well, in case that helps diagnose this. 

This is my first fastify project, so I'm not entirely sure what to be looking for to self-diagnose. I'd be happy to provide any further details if needed.

### Steps to Reproduce

I think it should be easy enough to reproduce with any simple fastify project, with the file to launch the server in a server/ folder, rather than the root.

### Expected Behavior

I generally expect it work on Windows as well, when it works on Linux and Mac.

**Comment by Eomm** [comment]
Could you check with the `-l debug` option and removing the pino-pretty piping?

In powershell the slash or backslash should be the same, but did you try it too?

**Comment by UmarGhouse** [comment]
Thanks @Eomm ! I tried doing what you said in different variations and here were the results:

- `fastify start -l debug -w server/fastify.js --options --ignore-watch='out.csv node_modules ui .nyc_output'`
- `fastify start -l debug -w server\fastify.js --options --ignore-watch='out.csv node_modules ui .nyc_output'` - note the backslash after `server`
- `fastify start server/fastify.js -l debug -w --options --ignore-watch='out.csv node_modules ui .nyc_output'` - note that `server/fastify.js` comes before the `opts` here

None of the above worked. However, when I did the following, it worked (sort of)!
- `fastify start -l debug -w server/fastify.js`
- `fastify start -l debug -w server/fastify.js -- --ignore-watch='out.csv node_modules ui .nyc_output'`

It didn't actually start the server (I got the error `bcrypt_lib.node is not a valid Win32 application.`), but at least it fixed the `missing file parameter` error. This leads me to believe that the `--options` flag isn't recognized on windows, even though it is on Mac and Linux, and it needs to be just `--` instead.

I tested using just `--` on WSL as well and it seems to work just fine, so I think that may be the solution here - what do you think?

**Comment by mcollina** [comment]
cc @simoneb could you take a look?

**Comment by simoneb** [comment]
@UmarGhouse replace single quotes with double quotes. If an npm script, escape them with backslashes, e.g.

```
"start2: "fastify start -w server/fastify.js --options --ignore-watch=\"out.csv node_modules ui .nyc_output\" | pino-pretty"
```

**Comment by UmarGhouse** [comment]
Thanks @simoneb ! It works when I use double quotes instead of single ones (escaped with backslashes as shown). Tested the same on WSL and it works there as well! Just the bcrypt error left, but I think I can solve that by re-installing my packages. 

So, I think we can close this issue 🙂. Thanks again!
