### ISSUE TITLE
Choose a custom logging framework

### ISSUE THREAD

**Issue by cunum** [fastify/fastify-cli#380]
Would be nice to be able to choose a logging framework via CLI argument, for example 

`--log-framework log4js`

And CLI would use this on app start

```
const app = Fastify({
  logger: require(loggingFramework)
})
```

**Comment by kibertoad** [comment]
@cunum Considering that pino is the best logging framework on the block, why might you want this?..

**Comment by cunum** [comment]
Sometimes you have to use your own logging framework, I'd guess every major company has at least its own fork, preference is another reason, you name it.

**Comment by kibertoad** [comment]
Makes sense :)

**Comment by cunum** [comment]
For the record, I found a CLI argument in the code that already does exactly this. 

So this can be closed, the argument is not documented (maybe a todo) yet, but with `-L` flag you can pass a custom logger.

**Comment by Eomm** [comment]
> logger: require(loggingFramework)

I don't think this API would work: are log4j and other logs out there supporting the same pino interface?

I would suggest a `optionHook` parameter that links a file that enance the fastify server option adding a logger instance and return it

**Comment by cunum** [comment]
As mentioned it's already implemented but not yet documented.

`'logging-module': ['L']`

In start.js:
```
let logger
if (opts.loggingModule) {
  try {
    logger = requireModule(opts.loggingModule)
  } catch (e) {
    module.exports.stop(e)
  }
}
```

I'm using it for a custom multi stream logging setup.

**Comment by Eomm** [comment]
I would leave the issue open to fix the docs 👍🏽

**Comment by meehawk** [comment]
@Eomm , slowly getting back to the flow! I'd like to take this up. In the meantime I'm going over a recent PR to try to catch things up. Can you guide me through this issue

**Comment by Eomm** [comment]
Oh, I think this PR https://github.com/fastify/fastify-cli/pull/410 covered this issue

But there are a lot of good-first-issue on our website: https://www.fastify.io/contribute/
if you are willing to help 😄 


closing
