### ISSUE TITLE
Memory leaks and high CPU usage with typescript on dev mode

### ISSUE THREAD

**Issue by mhmd-22** [fastify/fastify-cli#389]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.0.0

### Plugin version

cli-2.13.0

### Node.js version

16.3.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

When running "npm run dev" with the default typescript template that comes with cli. a crazy continuous memory leak and high CPU usage occur. sometimes it hits close to 1GB and 10% usage on 8 core CPU which is not good. the problem doesn't occur on npm run start or javascript template.

### Steps to Reproduce

1- run `fastify generate test --lang=ts`
2- run npm run dev

**Comment by StarpTech** [comment]
As far I can tell you this is normal. Typescript tooling consumes a lot of memory.

**Comment by zekth** [comment]
I tried on node 15 and 16 and i was not able to reproduce your problem. Can you explain more your context of use? Also please provide resource monitor informations. ( Win + R . 'resmon' )

**Comment by mhmd-22** [comment]
@StarpTech I've never encounter this on other typescript projects

@zekth I peak at 500-700Mb most of the time. and sometimes it didn't peak at all and it continue close to 1GB. it's inconsistent. and it depends on the number of dependencies.

I will try to do more testing and see what happens.

**Comment by mhmd-22** [comment]
As @StarpTech said. it's looks like a tooling issue with typescript. I tried different type of projects and the memory consumption is consistent depending on the project size. I'll close the issue for now as it's not affect the production.

**Comment by StarpTech** [comment]
It is really a problem. It can be reduced by disable type-checking. https://github.com/TypeStrong/ts-node#typechecking

**Comment by mhmd-22** [comment]
**Update:**
Looks like the issue is from "watch" feature in `fastify start ` not typescript. I removed it and my memory usage dropped from 600MB to 100MB max. (also CPU usage dropped significantly)

I replaced fastify-start with `nodemon` and `tsc -w` and it works perfectly

**Comment by vamshi9666** [comment]
@mhmd-22 what can be done to fix this ?

**Comment by Eomm** [comment]
This issue is ~1,5 years old 
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
