### ISSUE TITLE
How can I use ‘fastify’ as a global object in other files

### ISSUE THREAD

**Issue by MrYbo** [fastify/fastify-cli#390]
## 🚀 Feature Proposal

```javaScript
module.exports = async function (fastify, opts) {
  fastify.post('/', schema.check, async (req, reply) => {

  })
}
```
As shown in the above code, because fastify is bound with some values, I have to put the processing method of the request here. If I want to separate the processing method into a separate file, how can I use fastify in this file. Note that this fastify has already bound some custom global objects when the project starts.

## Motivation

Please outline the motivation for the proposal.

## Example

router.js 

```javaScript
module.exports = async function (fastify, opts) {
  fastify.post('/', schema.check, controller.handler)
```
controller.js
```javascript
async handler(req, reply) => {
  // I need to use some data bound on fastify here
}

**Comment by mcollina** [comment]
The `this` in your route is the fastify instance.

**Comment by MrYbo** [comment]
But I still don't quite understand how to use this global fastify instance created by cli when the project starts up in other files.Hope you can teach me. thank you very much

**Comment by mcollina** [comment]
Wrap them in plugins, and load them with register.
