### ISSUE TITLE
Upgrade blessed-contrib dep to latest 4.9.0 to avoid indirect vulnerabilities

### ISSUE THREAD

**Issue by lirantal** [fastify/fastify-cli#391]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

2.13.0

### Node.js version

14

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Description

The current version of the `blessed-contrib` dependency has some indirect vulnerabilities, so I went ahead with releasing a new version (4.9.0) with those indirect deps on blessed-contrib up to date now.

Note: the vulnerabilities by these indirect dependencies probably have no real impact on the project, but it's nicer to stay on an updated version of deps and those that don't introduce any issues.

### Steps to Reproduce

Scan the project for vulnerabilities

### Expected Behavior

No vulnerabilities reported for dependencies used by `fastify-cli`

**Comment by mcollina** [comment]
Should this be automatically picked up by tooling without any manual fix? The dependency update is in range.

**Comment by lirantal** [comment]
I notice now that there's no lockfile in the project, which is why I didn't want to PR this in the first place, and let the project update deps with whatever tooling they see fit.

That 4.9.0 less than an hour old so it'll probably take a bit for tooling to kick in before they suggest a dependency upgrade. Not sure what you're using right now but we can wait until it does. No real urgency here. It's a quick change I can PR, but wasn't sure if the project policy is to do it with tooling or manual updates would be fine too.

**Comment by mcollina** [comment]
No need, it will; be picked up by the tooling automatically!

**Comment by lirantal** [comment]
The Snyk bot just kicked-in with the blessed-contrib update: https://github.com/lirantal/dockly/pull/166

**Comment by seriousme** [comment]
FYI: Currently NPM audit reports another issue on `fastify-cli@2.15.0` because of`blessed-contrib` using `marked`.

**Comment by lirantal** [comment]
I maintain `blessed-contrib`, let me check what's the issue there.

**Comment by lirantal** [comment]
@seriousme @mcollina I published `blessed-contrib@4.11.0`

Can you run some sanity tests on the functionalities that rely on it? the framework doesn't have any tests so I had to ran some manual checks on my end of the library to make sure it doesn't break anything but want to give you a heads up before you push a new version of the fastify cli

**Comment by seriousme** [comment]
Just ran `npm audit fix` on my `fastify-openapi-glue` package which depends on `fastify-cli`. This installed `blessed-contrib@4.11.0`. Running `npm test` after that produced no errors with 100% code coverage.

Fastify-cli itself has dependabot active so `blessed-contrib@4.11.0` will automatically be picked up, tested and merged on succesfull test.
(e.g. see https://github.com/fastify/fastify-cli/pull/459)

@lirantal thanks for the fix !

**Comment by lirantal** [comment]
Sounds great!
