### ISSUE TITLE
Improved Documentation for containerization of fastify-cli

### ISSUE THREAD

**Issue by jeff-sexton** [fastify/fastify-cli#398]
## 🚀 Feature Proposal
 A small documentation update to add details regarding using `fastify-cli` within a container. This would add details about both the existing functionality to detect when a `fastify-cli` process is running in a docker container and highlight the need to explicitly set the server address to 0.0.0.0 for non-docker containers. 

## Motivation
`fastify-cli` has default behaviour to automatically detect when a server process is running within a docker container but this feature does not function when using containers that were not built with the docker daemon. Determining this difference and its cause took some digging so the information should be documented for others to use in the future. 

## Example

 We recently ran into an issue while migrating one of our applications from an OpenShift v3 instance to an OpenShift v4 instance. 

Our API application uses `fastify-cli` to start and manage a `fastify` server and is containerized for deployment in the OpenShift environments. 

Originally our application relied on the default behaviour of `fastify-cli` found [here](https://github.com/fastify/fastify-cli/blob/bb64f2e985e2cdd2e379197fd2b3ae4a4b5b3aae/start.js#L159-L160) which automatically detects that the server process is running within a Docker container and sets the server listen address to 0.0.0.0 for container compatibility.  The [`is-docker` library](https://github.com/sindresorhus/is-docker) is used to tell `fastify-cli` whether or not the server process is running in a Docker container. 

When we moved this same application to the OpenShify v4 environment, this default behavior stopped functioning and the containerized application pods were now starting at `127.0.0.1:3000` by default. This caused the server application to be unable to communicate with requests from outside the container. 

It turns out that one of the major changes between OpenShift v3 to v4 is that the Docker daemon is no longer used directly to build and run containers. OpenShift v4 now uses `buildah` and `podman` to perform these tasks. When these tools are used, the resulting container no longer includes the indicators that the `is-docker` library uses to identify a containerized process.

This is easy enough to fix by explicitly defining the listen address for `fastify-cli` when it starts using either CLI arguments or the `FASTIFY_ADDRESS` ENV variable. 

## Discussion

The issue is that this default container behaviour (and edge case) is not clearly documented. The main `fastify` documentation makes [reference](https://www.fastify.io/docs/latest/Server/#listen) to using the 0.0.0.0 address for docker containers but this information is not present for `fastify-cli`. `fastify` itself also seems to handle this slightly differently than `fastify-cli`. Only `fastify-cli` is configured to detect Docker containers and automatically set the address to 0.0.0.0. In 'fastify', it seems like this would always need to be set manually. 

I would be happy to open a PR and link it to this issue which adds a few lines to the `fastify-cli` documentation about this feature and the need to explicitly define the 0.0.0.0 address if the Docker daemon is _not_ used for containerization. This should make the issue easier to address for others in the future.

In addition to updating the documentation, would it be worth it to try and improve the existing container detection functionality? This would probably involve further research/experimentation with detecting _any_ containerized process instead of just Docker containers.

**Comment by mcollina** [comment]
Go and open a PR! I would also add that we could create a Dockerfile already as part of our templates.

**Comment by jeff-sexton** [comment]
Does the `fastify-cli` template include a Dockerfile? Or do you mean that we could create another template example that was ready for containerization?
