### ISSUE TITLE
Config File Option

### ISSUE THREAD

**Issue by galvez** [fastify/fastify-cli#401]
Would be nice to be able to pass `-c config.js` in the command line, a file that would export an object with this signature:

```
{
  port, 
  address, 
  socket, 
  require, 
  logLevel, 
  debug, 
  debugPort, 
  debugHost, 
  prettyLogs, 
  watch, 
  ignoreWatch, 
  verboseWatch, 
  options, 
  prefix,
  pluginTimeout,
  bodyLimit,
}
```

That is, a 1:1 mapping to all options configurable via environment variables.

Would you consider merging a PR implementing this feature?

**Comment by mcollina** [comment]
Sure thing!

**Comment by wlinna** [comment]
Is there a workaround for this? I am new to fastify, and I'd like to set trustProxy to true, but I have no idea how to do that when using fastify-cli.  #497  says that there isn't any way to set it, but is it true?

**Comment by Eomm** [comment]
Right now we have the `--options` flag that reads the JSON config from the app itself: https://github.com/fastify/fastify-cli#start

**Comment by nooreldeensalah** [comment]
I'm interested in working on this issue, but I wanted to inquire about a specific detail.

Let's say, for example, there's a `config.js` file with the following options

```javascript
module.exports = {
    port: 5000,
    prettyLogs: true
}
```

And the user while starting the application passed both `--config=config.js` and `--port=6000`, which port number should be given the priority, or should this return an error?
