### ISSUE TITLE
feat: Use ajv-compiler read/write feature

### ISSUE THREAD

**Issue by zekth** [fastify/fastify-cli#409]
## 🚀 Feature Proposal

Because https://github.com/fastify/ajv-compiler/commit/93fe638252149edc18e877c96eb45e4f3e742d7a has landed we are now able to use read/write feature of ajv validators.
One thing that would be great is to use fastify-cli to create the compiled schemas and being able to save them like snapshot for test runners. At the same time we need to consider a way to properly store them in source repositories and also to package them with service to ship for production ( eg: typescript builds)

## Motivation

Speed up the cold start of servers

**Comment by mcollina** [comment]
It would definitely be a great idea!
