### ISSUE TITLE
Async config options

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-cli#414]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Gives the user the possibility to set an `async` function to the `options` value to fetch some configuration from external resources

### Example

```
module.exports.options = async function load () {
  return {
    https: {
      key: await secretsManager
        .getSecretValue({ SecretId: 'https-key' })
        .promise(),
      cert: 'cert'
    }
  }
}
```

**Comment by mcollina** [comment]
The intent is to not have a user do that. Plugins and plugin dependencies should be used to fetch those values:

**Comment by Eomm** [comment]
The `options` object is provided to the `Fastify()` factory so the plugins load after the configuration has been set

**Comment by mcollina** [comment]
Take a look at https://www.nearform.com/blog/uncovering-secrets-in-fastify/, with those plugins you can load things at runtime.

**Comment by Eomm** [comment]
It is not possible having external settings such as the log level:

https://github.com/covidgreen/covid-green-backend-api/blob/91830ce825f3a0e1daa6822690c3a87779b19d35/lib/config/index.js#L272

**Comment by mcollina** [comment]
The logger level could easily be changed at runtime.

**Comment by Eomm** [comment]
Use case:
https://github.com/fastify/help/issues/568

**Comment by mcollina** [comment]
It's not needed to be asynchrounous.

**Comment by mcollina** [comment]
Note that this should support TLS.
