### ISSUE TITLE
Support build interface

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-cli#416]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Right now the test doc suggests to users to create a factory to build the fastify instance:

https://www.fastify.io/docs/latest/Testing/

```
function build(opts={}) {
  const app = fastify(opts)
  app.get('/', async function (request, reply) {
    return { hello: 'world' }
  })

  return app
}
```

This interface is easier to test for users and configure:

```
test('my test', t => {
  const fastify = build({})
  fastify.ready()
})
```

Instead, the `fastify-cli` interface requires  a simple plugin interface that force the user to write an helper that must know how `fastify-cli` works to instantiate it correctly.

```
function helper() {
   const app =Fastify(myApplication.config)
   app.register(myApplication)
   return app
}
```

### Motivation

So, this double interfaces does not fit togheter for newcomers and force the user to search for a pattern, instead of help them to find it.

For this reason, I think we should:

- expose the `build()` function that return a fastify intance when you `require('fastify-cli')`
- OR support the interface `build()` returned by the user, instead of the simple plugin interface

What do you think?

### Example

see above

**Comment by mcollina** [comment]
I think we should expose some helpers for tests and other programmatic access.
