### ISSUE TITLE
How to debug typescript project (VScode)

### ISSUE THREAD

**Issue by ilijaNL** [fastify/fastify-cli#426]
Hello,

I wonder if it is possible to use the debugger (VSCode or Chrome) on a typescript project generated with fastify-cli.

Thanks

**Comment by giacomorebonato** [comment]
It's possible to debug in VSCode by creating a `launch.json` file and picking the preset for **Node.js**.

![Screenshot 2021-11-11 at 11 25 51](https://user-images.githubusercontent.com/630796/141282283-931c49dd-9f89-4b9a-af76-0ec02c3b4ae3.png)

This is for example the `.vscode/launch.json` file that I get generated automatically:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/src/app.ts",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ]
        }
    ]
}
```

Sourcemaps also needs to be enabled in `tsconfig.json`

```json
{
    "extends": "fastify-tsconfig",
    "compilerOptions": {
        "outDir": "dist",
        "sourceMap": true
    },
    "include": ["src/**/*.ts"]
}
```

I tested this by putting a breakpoint on a project that I created with `fastify generate my-project --lang=ts`.

**Comment by giacomorebonato** [comment]
@ilijaNL could you check if this implementation achieves what you're looking for?

https://github.com/fastify/fastify-cli/pull/427#pullrequestreview-803935839

**Comment by ilijaNL** [comment]
> @ilijaNL could you check if this implementation achieves what you're looking for?
> 
> [#427 (review)](https://github.com/fastify/fastify-cli/pull/427#pullrequestreview-803935839)
Hmm cant get working on my project, npm run dev works fine but when starting with vs code it just closes after few seconds.

One thing about the suggestion is that it is not supporting watchers, and in my case always debug during development (using watch function)

**Comment by giacomorebonato** [comment]
@ilijaNL do you have sample project where I can reproduce the issue?
It works for me when starting a new project from scratch.

> Hmm cant get working on my project, npm run dev works fine but when starting with vs code it just closes after few seconds.

Do you have any output in VSCode "Debug Console" panel?

> One thing about the suggestion is that it is not supporting watchers

I am not prepare about this topic, hence sorry if I ask you a dumb question: does VSCode "Watch" panel allow to achieve what you intend to?

![Screenshot 2021-11-15 at 09 22 58](https://user-images.githubusercontent.com/630796/141747128-85c76cab-3dd4-4a7b-b56c-eb15d7cbedf0.png)

**Comment by giacomorebonato** [comment]
@ilijaNL would you give the command another try? I added livereload to the PR by re-using the existent `npm run dev` script.

I recap the steps to try it out:

* `git clone git@github.com:giacomorebonato/fastify-cli.git`
* `git checkout giacomorebonato:vscode_ts_debug`
* `node ./cli.js generate ../my-fastify-ts --lang ts`

Please let me know if this change satisfies what you're trying to achieve.
