### ISSUE TITLE
Generated project is restarting the server for git changes

### ISSUE THREAD

**Issue by gingermusketeer** [fastify/fastify-cli#433]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

CLI 2.13.0 

### Node.js version

16.13

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.1

### Description

Changes to files unrelated to the Fastify server (for example anything in .git) is triggering the server to restart. 

![Skjermbilde 2021-11-24 kl  15 42 18](https://user-images.githubusercontent.com/1177034/143261050-130e4fac-c6c0-470c-84ac-7e1606a34aad.png)

![Skjermbilde 2021-11-24 kl  15 54 17](https://user-images.githubusercontent.com/1177034/143261115-214b5b4d-8832-4b4d-8fcf-f504f4de2ced.png)

### Steps to Reproduce

1.  Run `fastify generate --lang ts fastify-ts-reboot-loop && cd fastify-ts-reboot-loop && git init`
2. Add `--verbose-watch` to `dev` npm script.
3. Run `npm run dev`
4. Commit a file

### Expected Behavior

Fastify server only restarts for JS files that have changed.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gingermusketeer** [comment]
@mcollina Looking into where the issue might be I think it is caused by `--ignore-watch=.ts$` in package.json replacing the default values for `--ignore-watch`.

What do you see as being a good solution here? The flag could be made additive only but then that will be a bit restrictive perhaps?

**Comment by mcollina** [comment]
I think the additive solution you are proposing is ok.

**Comment by a-eid** [comment]
I can not add extra files to `--ignore-watch`, it is so confusing.

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
