### ISSUE TITLE
How to mock components?

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-cli#453]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Using the test utility introduced here https://github.com/fastify/fastify-cli/pull/446

```
async function buildApp (t, env) {
  const app = await fcli.build(startArgs, config({ ...defaultEnv, ...env }))
  t.teardown(() => { app.close() })
  return app
}
```

How could the user mock some components?
Is this the only way?

```
  Object.keys(require.cache).forEach(function (key) { delete require.cache[key] })
  require(path)
  require.cache[require.resolve(path)].exports = {
    async store () {
      throw new Error('This should be called')
    }
  }
  t.teardown(() => {
    Object.keys(require.cache).forEach(function (key) { delete require.cache[key] })
  })
```

**Comment by mcollina** [comment]
Use proxyquire or testdouble (for esm). But truly, you should never do this. Just test the individual plugins as unit (by loading in an vanilla Fastify instance) instead.
