### ISSUE TITLE
Links in README of Typescript template are broken

### ISSUE THREAD

**Issue by braekevelt** [fastify/fastify-cli#456]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

2.15.0

### Node.js version

14.18.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

The links inside `src/routes/README.md` and `src/routes/README.md` are broken because the fastify website now groups pages as "Guides" or "Reference". For example https://www.fastify.io/docs/latest/Decorators/ should instead be https://www.fastify.io/docs/latest/Reference/Decorators/.

### Steps to Reproduce

Generate an app using `npx fastify-cli generate app --lang=ts`.
Click on [decorators](https://www.fastify.io/docs/latest/Decorators/) in `app/src/routes/README.md`.
See `Error 404 Content not found`

### Expected Behavior

The docs should be visible instead.

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by braekevelt** [comment]
Hmm, this issue is already fixed in master 15 days ago by @rush1506: https://github.com/fastify/fastify-cli/commit/51e1cf706978be514120356e562984cd820a2858#diff-9cf3cdd3514ee512c637fee256b74ffd69947675184924e927eb2321d13d9c6e
