### ISSUE TITLE
Typescript tests in subfolder of routes are not executed

### ISSUE THREAD

**Issue by braekevelt** [fastify/fastify-cli#457]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

2.15.0

### Node.js version

14.18.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

If you move `app/test/routes/example.test.ts` to `app/test/routes/subfolder/example.test.ts`, it is not longer executed when running `npm run test`. This can be fixed by changing `tap --ts test/**/*.test.ts` to `tap --ts test/plugins test/routes`.

### Steps to Reproduce

Generate an app using `npx fastify-cli generate app --lang=ts`.
Run `npm run test`.
Observe that 3 tests are executed.
![image](https://user-images.githubusercontent.com/28069994/152558577-5e2ec733-9caa-4a11-870e-8b01a6a7a6c2.png)

Create a folder `subfolder` inside `app/test/routes`.
Move `app/test/routes/example.test.ts` to `app/test/routes/subfolder/example.test.ts`.
Run `npm run test`.
Observe that only 2 tests are executed.
![image](https://user-images.githubusercontent.com/28069994/152558688-ad401220-d5b2-439b-a215-4e07a080a836.png)

### Expected Behavior

Moving tests to subfolders should not prevent their execution.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by KXLAA** [comment]
I could try to sort this out if @braekevelt doesn't want to

**Comment by braekevelt** [comment]
@KXLAA you can make the Pull Request if you want to. Thank you!

**Comment by is2ei** [comment]
I guess we don't need to specify each subdirectory.

```
tap --ts test/plugins test/routes
```

The command below is enough.

```
tap --ts
```

https://node-tap.org/docs/cli/
> By default, tap will search for all files ending in
> .ts, .tsx, .js, .jsx, .cjs, or .mjs, in a top-level
> folder named test, tests, or __tests__, or any file
> ending in '.spec.' or '.test.' before a supported
> extension, or a top-level file named
> 'test.(js,jsx,...)' or 'tests.(js,jsx,...)'

**Comment by is2ei** [comment]
I found `fastify-cli` uses `minimatch` for unit testing but `tap` uses `glob`.

https://github.com/fastify/fastify-cli/blob/master/test/generate-typescript.test.js#L143-L145

https://github.com/tapjs/node-tap/blob/43bf1df7d83287ac419c9b1ad7e9c033fe3aded5/bin/run.js#L434-L439

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fastify-cli/pull/506
