### ISSUE TITLE
Fastify cli does not work in windows 10 and windows 10 professional

### ISSUE THREAD

**Issue by waqastanoli** [fastify/fastify-cli#467]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

2.15.0

### Plugin version

none

### Node.js version

14.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

19044.1566

### Description

Fastify cli does not work in windows 10 and windows 10 professional, it works on mac OS fine, but I have tried on different windows 10 machines, and it gives the same behavior.
![image](https://user-images.githubusercontent.com/11660304/156134130-4eac2c36-2596-461e-a1cc-b7d6809cefb3.png)

### Steps to Reproduce

```npm install fastify-cli --global```

```fastify```

### Expected Behavior

fastify cli should work on windows as it does on mac OS.

**Comment by waqastanoli** [comment]
tried both npm and yarn to add the package same behavior. issue is in
```node_modules\marked-terminal\index.cjs```

```
'use strict';

var process$1 = require('node:process');
var os = require('node:os');
var tty = require('node:tty');
var Table = require('cli-table3');
```

**Comment by darkgl0w** [comment]
node internal syntax (e.g.: `node:<internal_module_name>`) is not supported by Node.js 14.16.0

**Comment by waqastanoli** [comment]
It worked, Thanks allot @darkgl0w

**Comment by johntom** [comment]
Hi,
I just removed all nodejs versions to try to fix error with fastify-cli and installed both 16.15.0 and 14.18.3 with nvm.
No matter when irun npm install or yarn add I get the following
                                                                    
D:\devel\htmx-fastify\my-app                                        
fastify                                                           
'fastify' is not recognized as an internal or external command,     
operable program or batch file.                                     

my ennvionment
Edition	Windows 10 Home
Version	21H1
Installed on	‎2/‎15/‎2021
OS build	19043.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by waqastanoli** [comment]
> 



> Hi, I just removed all nodejs versions to try to fix error with fastify-cli and installed both 16.15.0 and 14.18.3 with nvm. No matter when I run npm install or yarn add I get the following error
> 
> D:\devel\htmx-fastify\my-app fastify 'fastify' is not recognized as an internal or external command, operable program or batch file.
> 
> my ennvionment Edition Windows 10 Home Version 21H1 Installed on ‎2/‎15/‎2021 OS build 19043.1645 Experience Windows Feature Experience Pack 120.2212.4170.0

@johntom did you insall fastify cli globally?
``npm install fastify-cli --global``
https://github.com/fastify/fastify-cli#install

**Comment by johntom** [comment]
Hi,
I'm back on this as I want to start a fresh project as I'm having issues with fastify socket since doing some upgrades. 
Windows 10 Home  V: 21H1 OSBuild 19043.1766
Im using nvm and uninstalled and reinstalled all versions
1) I installed  npm install fastify-cli --global for
17.5.0
16.15.0
14.18.3
2) all give me the same error
```

PS D:\devel\fastifycli> fastify
fastify : The term 'fastify' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ fastify
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (fastify:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
