### ISSUE TITLE
Custom logging framework do not work with ESM projects

### ISSUE THREAD

**Issue by alexandervu** [fastify/fastify-cli#478]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Node.js version

14.19.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10 and MacOS 12.3.1

### Description

Defining Custom logging using `logging-module` option do not work. 
When using ESM JS file the error is: 

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <path>\log.js
require() of ES modules is not supported.
```

Renaming the file to CommonJS `log.cjs` result in an other error.

```
Error: Cannot find module '<path>\log'
```

The only workaround for this I found, was to create a second file. The missing file `log` and `require` and `module.export` the logger from the origin file `log.cjs` there.
It would be great if we can use here EMS files, or handle the `cjs` file extension right way. 

### Steps to Reproduce

Create new project using `fastify-cli`. 
Create file `log.js` in the project root, using this content for testing purpose:

```js
module.exports = {
  name: 'Custom Logger',
  customLevels: {
    test: 99
  }
}
```

Now update the `dev` script task in `package.json` by adding the `--logging-module`.
```
"dev": "fastify start app.js --log-level debug --logging-module ./log.js --watch"
```

Rename and test with the file like described in the description.

**Comment by mcollina** [comment]
Good spot! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by denes-fekeshazy** [comment]
There has been a few updates to `fastify` and `fastify-cli` since the issue has been raised. So I have figured I should verify if the issue is still present in the latest version of these packages. Using the provided "steps to reproduce" I was not able to encounter the raised issue using the latest `fastify` and `fastify-cli` versions.
@alexandervu, could you please verify if you are still experiencing the same issue?

**Comment by mil7** [comment]
Unfortunatly this issue is still a present one.

But there exists a workaround: Additional to the `log.cjs` you have to create a file `log` (without any file endings) and this content:

```js
const log = require('./log.cjs')

module.exports = log
```
