### ISSUE TITLE
Fastify generate use deprecated libraries

### ISSUE THREAD

**Issue by Roxxas96** [fastify/fastify-cli#480]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

2.15.0

### Node.js version

16.14.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

manjaro-release 21.2.6-1

### Description

The `fastify generate` command generate a project with two libraries : `fastify-sensible` and `fastify-autoload` which are deprecated since respectively `3.2.0` and `3.13.0`. For classic JS projects it's not blocking but for TS projects it generates an error during transpiling into pure JS due to "implicit `any` types" :

```
src/plugins/sensible.ts:2:43 - error TS7016: Could not find a declaration file for module 'fastify-sensible'. 'node_modules/fastify- 
sensible/index.js' implicitly has an 'any' type. Try `npm i --save-dev @types/fastify-sensible` if it exists or add a new declaration  
(.d.ts) file containing `declare module 'fastify-sensible';`
```

```
src/app.ts:2:47 - error TS7016: Could not find a declaration file for module 'fastify-autoload'. 'node_modules/fastify- 
autoload/index.js' implicitly has an 'any' type. Try `npm i --save-dev @types/fastify-autoload` if it exists or add a new declaration  
(.d.ts) file containing `declare module 'fastify-autoload';`
```

### Steps to Reproduce

- Start a new fresh project with `fastify generate --lang=ts test`
- Run `npm install`
- Run `npm run build:ts`

### Expected Behavior

The project should have up to date dependencies so `tsc` can transpile our code without changing the two libraries by hand.

**Comment by Roxxas96** [comment]
Hey ! This is the first Issue of my life on an open-source project. I apologize for any mistakes I could have done ! I would apreciate all your comments/advice 😁.

**Comment by climba03003** [comment]
The template need to be updated to use the latest `scoped` module.
Would you like to send a PR to address this issue?

**Comment by Roxxas96** [comment]
Why not ! I'll fork the project and try to submit a PR as soon as possible.

**Comment by miquelfire** [comment]
Looks like #479 took care of this.

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fastify-cli/releases/tag/v3.0.0.
