### ISSUE TITLE
New project is generated without dependencies on namespaced @fastify/sensible, and @fastify/autoload

### ISSUE THREAD

**Issue by segevfiner** [fastify/fastify-cli#483]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

cli (3.0.0)

### Node.js version

16.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1

### Description

A newly generated Fastify project using fastify-cli is generated without dependencies on `@fastify/sensible`, and `@fastify/autoload` in its `package.json`.

### Steps to Reproduce

1. Run `fastify generate fastify-test --lang=ts`
2. Check the `package.json`.

### Expected Behavior

The newly generated project should have all proper dependencies for it to work.

**Comment by climba03003** [comment]
Duplicated #480

**Comment by mcollina** [comment]
Fixed in https://github.com/fastify/fastify-cli/releases/tag/v3.0.0.

**Comment by segevfiner** [comment]
@mcollina I just tried this with v3.0.0 and it happened...
