### ISSUE TITLE
Help is not printed: There are 8 help pages that matches the given result 

### ISSUE THREAD

**Issue by skizer** [fastify/fastify-cli#492]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0

### Node.js version

16.14.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

When using ´fastify´ it doesn't print the expected help information but rather this output

```
There are 8 help pages that matches the given request, please disambiguate:
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/eject-ts
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/eject
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/generate-plugin
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/generate
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/help
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/print-routes
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/readme
  C:/Users/Matt/AppData/Roaming/nvm/v16.14.2/node_modules/fastify-cli/help/start
  ```

### Steps to Reproduce

`npm i fastify/fastify-cli -g`
`fastify`

### Expected Behavior

Should print the help information according to the githubs readme.

```
Fastify command line interface, available commands are:

  * start                 start a server
  * generate              generate a new project
  * generate-plugin       generate a new plugin project
  * readme                generate a README.md for the plugin
  * print-routes          prints the representation of the internal radix tree used by the router, useful for debugging.
  * version               the current fastify-cli version
  * help                  help about commands

Launch 'fastify help [command]' to know more about the commands.

The default command is start, you can hit

  fastify start plugin.js

to start plugin.js.
```

**Comment by mcollina** [comment]
@simoneb could you take a look? This looks a windows issue

**Comment by simoneb** [comment]
I don't see anything particularly strange about this. You're invoking fastify-cli (whose executable name is just fastify once you install it globally) with no command, so it prints the help by default. The global help just lists the pages that contain help, so you either need to specify a command (e.g. fastify start) or if you want to show the help you need to invoke it with a command (e.g. fastify help start).

**Comment by mcollina** [comment]
I think the problem is that the list has full windows paths in them
