### ISSUE TITLE
LGTM-Alert: Unreachable Code

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fastify-cli#510]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Node.js version

any

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

any

### Description

This if-condition is always false:
https://github.com/fastify/fastify-cli/blob/89785005a5df4803d14ded005dfec318d8c7923a/lib/watch/index.js#L51

https://lgtm.com/projects/g/fastify/fastify-cli/snapshot/e526bf426fca7776295b2bbc415a9de4a7e83ca6/files/lib/watch/index.js?sort=name&dir=ASC&mode=list#xce7f5b7c7484a77e:1

### Steps to Reproduce

-

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
