### ISSUE TITLE
--watch option is not working

### ISSUE THREAD

**Issue by tehla** [fastify/fastify-cli#527]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Node.js version

16.14.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

alpine3.14

### Description

Hello

I'm trying to mount a dev stack with fastify-cli inside. 
I was expecting my app to restart when I'm modifying a src/ file, but it doesn't.
I was looking for similar issues, but nothing is matching to my use case.

Need some help please

### Steps to Reproduce

You have my project on https://github.com/tehla/js-stack/tree/fastify-app

`docker-compose build`
`docker-compose up-d`
go into the node container
`bash` if you want
`cd app`
`npm run dev`
and try to modify the src code

**Comment by mcollina** [comment]
As far as I'm aware, watching file is not supported over docker. I would recommend to avoid using docker for development.

**Comment by acardinale** [comment]
You can try setting the CHOKIDAR_USEPOLLING environment variable to 1

`env CHOKIDAR_USEPOLLING=1 fastify start -p 3001 -w -l info -P -o app.js`
