### ISSUE TITLE
Support ESM on generate (optional)

### ISSUE THREAD

**Issue by ram-you** [fastify/fastify-cli#539]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Is there a way to make fastify-cli generate code with esm modules (optional)?

### Example

`fastify generate folderName --esm`

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by nooreldeensalah** [comment]
I would like to work on this!

**Comment by mcollina** [comment]
go for it!
