### ISSUE TITLE
support a --help flag for intuitive usage

### ISSUE THREAD

**Issue by evanshortiss** [fastify/fastify-cli#543]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Adding a `--help` flag to improve developer experience.

### Motivation

I wanted to generate a project, but was curious about customisation aspects. I ran `fastify generate ---help` but this printed an error `must specify a directory to 'fastify generate'`

This was surprising. I expect most CLIs to accept a `--help` flag.

### Example

I would expect that when you type `fastify generate --help` that it will output the same content as `fastify help generate`, i.e

```
Usage: fastify generate <FOLDER>

Sets up project with `npm init -y` and
generates a sample Fastify project
in the <FOLDER>. Specify `.` to create files in the current working directory.

OPTS

  --integrate
      overwrite it when the target directory is the current directory (.)

  --lang=ts, --lang=typescript
      use the TypeScript template

  --standardlint
      for JavaScript template, optionally includes linter to fix code style issues
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by evanshortiss** [comment]
Happy to take a look and try my hand at a PR 👍

**Comment by Eomm** [comment]
Merged in https://github.com/fastify/fastify-cli/pull/544

Thks for your contribution!
