### ISSUE TITLE
watch mode not working with esm

### ISSUE THREAD

**Issue by monkoninja** [fastify/fastify-cli#547]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Node.js version

16.13.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

server does not restart after editing files if esm is used

### Steps to Reproduce

```
fastify generate app --esm
cd app
npm i
npm run dev
```
change any file -> server does not restart

without esm it's working.

**Comment by nooreldeensalah** [comment]
I couldn't reproduce this on my end, watch mode is working as expected in the esm template.
My environment:
`OS`: Windows 10 (21H1)
`Node`: 16.17.0
`Fastify-CLI`: 5.4.1

**Comment by monkoninja** [comment]
> I couldn't reproduce this on my end, watch mode is working as expected in the esm template. My environment: `OS`: Windows 10 (21H1) `Node`: 16.17.0 `Fastify-CLI`: 5.4.1

I updated nodejs to 16.17.0 and it works now.

**Comment by mrlectus** [comment]
mine is not working also am on v6, how did you fix this?
