### ISSUE TITLE
How to start http2 server using fastify-cli

### ISSUE THREAD

**Issue by nileshmali** [fastify/fastify-cli#56]
I am trying to write microservices for one of application by refering [fastify-example-twitter](https://github.com/fastify/fastify-example-twitter/tree/refatorize-as-suggested). 
I want those to be http2 enabled without ssl for internal communication between microservices. 
Is there any way I could enable http2 while using fastify-cli for bootstraping microservice.

**Comment by delvedor** [comment]
You can add `module.exports.options` as shown [here](https://github.com/fastify/fastify-cli/blob/master/examples/plugin-with-options.js). Those options will be passed to the Fastify instance :)
