### ISSUE TITLE
Command to generate swagger/openapi schema from @fastify/swagger

### ISSUE THREAD

**Issue by segevfiner** [fastify/fastify-cli#563]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be cool to have a CLI command to generate the swagger/openapi schema that [@fastify/swagger](https://github.com/fastify/fastify-swagger) generates to a file.

### Motivation

So that I won't have to start the server or eject and write a custom script to achieve this.

(Could make sense as a plugin for fastify-cli itself, but I don't think fastify-cli supports plugins supplying custom commands)

### Example

```
fastify generate-swagger server.js > openapi.json
```

Which will essentially call `fastify.swagger()` and print it out. Of course, output file flags, flag to generate yaml, etc. Are also welcome.

**Comment by mcollina** [comment]
We have some code for doing this in Platformatic: https://github.com/platformatic/platformatic/blob/main/packages/db/lib/gen-schema.mjs

I don't think this should be part of fastify-cli as having an OpenAPI definition is likely too opinionated.

**Comment by segevfiner** [comment]
As just a subcommand, or as a plugin to fastify-cli itself? Or an external command that uses some the same code that fastify-cli uses to import the app (Which might not be exported ATM)?

**Comment by mcollina** [comment]
The problem is that this does not bundle `@fastify/swagger`, so how would you add this plugin to the CLI?

**Comment by segevfiner** [comment]
Condtionally at runtime, the user will have to install it in is app, we will only check if it exists on the app instance rather than try to use our own copy.

**Comment by mcollina** [comment]
I would love to see how you'd implement this. However I'm not sure this would land.
