### ISSUE TITLE
`fastify generate <dir> --esm --lang=ts`  doesn't generate esm enabled ts project

### ISSUE THREAD

**Issue by vishal-mmnm** [fastify/fastify-cli#577]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Node.js version

18.12

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

`fastify generate` doesn't seem to work well when multiple options are provided. `fastify generate . --esm` & `fastify generate . --lang=ts` both seem to work well. But, combining options `fastify generate . --esm --lang=ts` doesn't seem to create esm support in the generated ts project. 

### Steps to Reproduce

```
mkdir foo && cd foo && fastify generate . --esm --lang=ts
```

### Expected Behavior

The expected behavior is to generate an esm enabled typescript project

**Comment by mcollina** [comment]
I don't think we have template for esm and ts at the same time.

Would you like to contribute one?

**Comment by vishal-mmnm** [comment]
Thanks @mcollina for following up so promptly. Unfortunately, I don't have time to contribute this at the moment. I hope someone else can take this.

**Comment by S-Abhishek** [comment]
Hey, just a heads up. I am having a look at this, will create a PR soon.

**Comment by mcollina** [comment]
Thanks!

**Comment by vishal-mmnm** [comment]
Thanks @S-Abhishek

**Comment by nibravo** [comment]
Hello everyone.

I tried to use the CLI without --esm

`fastify generate <dir> --lang=ts`
`cd <div>`
`npm install`
`fastify start --port <port> src/app.ts`

But I get the error from the example plugins: 

```
import { join } from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

I could find a guide on how to use the typescript template using the CLI.
Any idea how to able to use the CLI with typescript?
Thank you in advance

**Comment by mcollina** [comment]
Done in https://github.com/fastify/fastify-cli/pull/585
