### ISSUE TITLE
Expose the Fastify options type 

### ISSUE THREAD

**Issue by meotimdihia** [fastify/fastify-cli#591]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, we have to write type for AppOptions, while it is Fastify options. And why we can't improve by importing the Fastify options type? It should be easier to code if we can do it. For example, I don't know what is logger type looks like.

https://github.com/fastify/fastify-cli/blob/master/templates/app-ts/src/app.ts#L5

```ts
export type AppOptions = {
  // Place your custom options for app below here.
  logger: <???>
  trustProxy: true,
  maxParamLength: number,
  connectionTimeout: number,
  requestTimeout: number,
  bodyLimit: number,
  exposeHeadRoutes: boolean,
  rewriteUrl: (req: FastifyRequest) => any, // I have to use <any> for this ...
  ajv: {
    customOptions: {
      removeAdditional: boolean,
      useDefaults: boolean,
      coerceTypes: string
      allErrors: boolean,
      allowUnionTypes: boolean,
    },
    plugins: any[]
  } 
} & Partial<AutoloadPluginOptions>;
```

### Motivation

Improve the plugin. Take advantage of Typescript type.

### Example

```ts
export type AppOptions = FastifyOptions & Partial<AutoloadPluginOptions>;
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
