### ISSUE TITLE
TypeScript AppOptions are not provided to app unless passed via CLI

### ISSUE THREAD

**Issue by evanshortiss** [fastify/fastify-cli#593]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Node.js version

18.12.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6.3

### Description

The TypeScript template allows us to provide options using the following in *app.ts*, however the `opts` variable passed to the `app` object doesn't contain my hardcoded options, e.g `foo` in the sample code below. Options provided with the CLI **do** appear in the object. Sample code:

```ts
export type AppOptions = {
  foo: string
  // Place your custom options for app below here.
} & Partial<AutoloadPluginOptions>;


// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {
  foo: 'bar'
}

const app: FastifyPluginAsync<AppOptions> = async (
    fastify,
    opts
): Promise<void> => {
  // Place here your custom code!
  console.log(opts.foo) // should print "bar"

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  })

  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })
};
```

The example `SupportPluginOptions` in the TS template receives an object like so: `{ prefix: undefined }`, which doesn't align with the `SupportPluginOptions`.

I might be opening a can of worms here about how the options functionality is supposed to work? The reason I ran into this issue is because I wanted to supply environment variables to my plugins via the `options` object. The solution I came up with was to modify the code to load plugins like so:

```ts
const options: AppOptions = {
  foo: 'bar',
  env: {
    maxValue: process.env.MAX_VALUE
  }
}


// Then inside the "app" function I use object.assign
void fastify.register(AutoLoad, {
  dir: join(__dirname, 'plugins'),
  options: Object.assign({ options }, opts)
})
```

### Steps to Reproduce

1. Generate a TS project: `npx fastify-cli@5.7.1 generate --lang=ts autoload-options`
1. Define custom `AppOptions` with some defaults (see example above)
1. Run code and notice that options are missing

### Expected Behavior

I would expect my default value for the property `foo` to be present since I hardcoded it in the `options` object, but it isn't applied unless I update the `opts` with `Object.assign`. I also found the generic type information for the plugins misleading since they appear receive the global `AppOptions`, and not the generic that's specified in the template.

Should the template be updated to correctly reflect types in the default plugins? Is it considered OK to use `Object.assign` like I am in my workaround to apply defaults?

**Comment by climba03003** [comment]
This is the main problem `Object.assign({ options }, opts)`
You place the `options` inside the `object` as a property. 
Which means `foo` is actually default for `options.options.foo` not `options.foo`.

**Comment by evanshortiss** [comment]
I probably should've been clearer. That was my workaround.

My primary issue is that, using the default template and simply changing:?

```
// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {}
```

to:

```
// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {
  foo: 'bar'
}
```

Does not work, so it's not clear how to add defaults without modifying the lines that are marked as `// Do not touch the following lines`.

**Comment by askmrsinh** [comment]
Currently dealing with the same issue.

```js
export type AppOptions = {} & Partial<AutoloadPluginOptions> & EnvOptions;

const schema = {
  type: 'object',
  required: ['PORT'],
  properties: {
    PORT: { type: 'number', default: 3000 }
  }
};

// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = { dotenv: true, expandEnv: true, schema };

const app: FastifyPluginAsync<AppOptions> = async (fastify, options): Promise<void> => {
  // Place here your custom code!

  console.log(options);                                                   // <----- this is always undefined
  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options
  });

  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options
  });
};

export default app;
export { app, options };
```

Command I am using (added `--options`):
```
fastify start --ignore-watch=.ts$ -w -l info -P --options dist/app.js
```

**Comment by jetchegoyen** [comment]
I'm facing the same issue as @askmrsinh. Any updates?

**Comment by dhensby** [comment]
I'm coming up against this and have done a little debugging to see what is going on. The crux of it is that the options (which are stored as `file.options`) never get passed to the `fastify.register()` call that the `start` cli script performs: https://github.com/fastify/fastify-cli/blob/v6.1.1/start.js#L149

The options *are* added to the server options and sent to the `Fastify` instance, but there is no way (that I can find) to access that because they are stored as a "private" `Symbol` on that fastify instance. There's a little confusion here because the app options are extended from the `FastifyServerOptions` (at least in the current template), so it seems to serve a dual purpose of defining options both for the "app" plugin and the server instance.

I'll try and author a quick patch and see what the feedback is.
