### ISSUE TITLE
Can't access plugin inside tests

### ISSUE THREAD

**Issue by thales-maciel** [fastify/fastify-cli#622]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I've generated the project using the cli and then I modified my app.ts file so that it looks like this:
```
import { join } from 'path';
import AutoLoad, {AutoloadPluginOptions} from '@fastify/autoload';
import { FastifyInstance, FastifyPluginAsync } from 'fastify';
import { fastifyPostgres } from '@fastify/postgres';
import fastifySwagger from '@fastify/swagger';
import fastifySwaggerUi from '@fastify/swagger-ui';
import sensible from '@fastify/sensible';
import cors from '@fastify/cors'

export type AppOptions = {} & Partial<AutoloadPluginOptions>;


// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {}

const app: FastifyPluginAsync<AppOptions> = async (fastify: FastifyInstance, opts: any): Promise<void> => {
  fastify.register(sensible)

  fastify.register(fastifyPostgres, {
    connectionString: `postgres://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}/${process.env.DB_DATABASE}`
  })

  fastify.register(fastifySwagger, { hideUntagged: true })
  fastify.register(fastifySwaggerUi, {
    routePrefix: '/docs',
    uiConfig: { docExpansion: 'list' }
  })

  await fastify.register(cors, {})

  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  })

}

export default app;
export { app, options }
```

The problem is that when i try to use the pg plugin inside a test I get an error `Cannot read properties of undefined (reading 'query')`, which makes me believe that the plugin hasn't been registered, but I don't know how to do it.

**Comment by fech-dev** [comment]
I have notice that the `build()` function does not wrap the app plugin (exported in src/app.ts) with `fp()` function.
I've tried to apply fp function and I can access all decorators defined. 
I don't know if this is intentional or not....

**Comment by Hornwitser** [comment]
I noticed the same, Wrapping the app into fastify-plugin was just randomly removed in #446 with this change https://github.com/fastify/fastify-cli/commit/6dfee4e393573031343c4b932f40c54b7a0f7f65#diff-d422baf24ac606e8462ae86c1d33235f3c9299defa513b127d36661e3d766e9dL20-R24. @Eomm why was this feature removed while confusingly keeping the comment that is clearly no longer correct?

FWIW I found a viable workaround by adding the following to the end of app.js, and then setting `process.env.NODE_ENV = "testing"` in test/helpers.js before it calls buildApplication.
 ```js
if (process.env.NODE_ENV === "testing") {
  // Ensure tests can access all decorators
  app[Symbol.for("skip-override")] = true;
}
```

**Comment by Eomm** [comment]
If @Hornwitser found the issue, would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Hornwitser** [comment]
I'm not sure how to solve this issue, I'm rather unfamiliar with fastify.

**Comment by SumeetHaryani** [comment]
@Eomm I would like to work on this issue

**Comment by Eomm** [comment]
Go for it!

**Comment by CorentinND** [comment]
Any update on this ?

**Comment by jean-michelet** [comment]
Looking into it, there are several things to improve here.
I think we should respect more open/close principle and allow users to decorate the app before `ready` is called.

**Comment by jean-michelet** [comment]
Maybe I should create a more general issue about refactoring, to make sure I understand how it (should) works, it could also be a lack of documentation.
