### ISSUE TITLE
Use Node.js built-in test runner in templates

### ISSUE THREAD

**Issue by piranna** [fastify/fastify-cli#632]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

In same spirit to https://github.com/fastify/fastify-cli/issues/631, use the Node.js built-in test runner instead of tap, they are mostly compatibles and would remove an extra dependency.

### Motivation

Use standard built-in modules and reduce dependencies.

**Comment by piranna** [comment]
I admit Node.js test runner is pretty new, just started on Node.js 18, so maybe it would be implemented behind a flag until all maintained versions have support for it (about two years from now) and later remove the flag and enable it by default.

**Comment by piranna** [comment]
Since now Node.js 18 is the oldest maintained version, can we implement this now? :-)

**Comment by mcollina** [comment]
Let's do it.

**Comment by piranna** [comment]
Great, I'll try to find some time to do a PR, I have just today created a new Fastify project and after upgrading dependencies, found that `tap` 18 has some compatibility issues when using ESM + Typescript, so the moment is perfect :-)
