### ISSUE TITLE
Add support for generate-swagger to generate in YAML format

### ISSUE THREAD

**Issue by segevfiner** [fastify/fastify-cli#661]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The `fastify.swagger()` API also supports a `{ yaml: true }` argument to get a YAML string. It would be nice to expose this from `generate-swagger`.

I would have implemented this myself, maybe even with an `-o file.txt` output file support. But I'm not sure how to add custom arguments for just this command with the way `parseArgs` works.

### Motivation

OpenAPI schemas are often represented in YAML for readability, and its already supported by `fastify.swagger()` just need to expose this in the CLI.

### Example

```sh
fastify generate-swagger --yaml -o openapi.yaml dist/app.js
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by segevfiner** [comment]
Yeah. Just what should I use to parse the arguments?

**Comment by mcollina** [comment]
yargs-parser
