### ISSUE TITLE
Generated project doesn't work out of the box with --esm --lang=ts

### ISSUE THREAD

**Issue by artur-demidov** [fastify/fastify-cli#680]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.0.0

### Plugin version

^4.0.0

### Node.js version

21.2.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.1

### Description

Project clean generated
When run the `npm run dev`, get an error

```
tsconfig.json:7:15 - error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

7     "module": "ES2022",
                ~~~~~~~~
```

_Same on windows 11. `npm` ver 10.2.4._ 

### Steps to Reproduce

```
npx fastify-cli generate test --lang=ts --esm
cd test
npm i
npm run dev
```

**Comment by big-kahuna-burger** [comment]
@mcollina this should have been closed with v6 release

**Comment by mcollina** [comment]
thx
