### ISSUE TITLE
Route URL case sensitivity

### ISSUE THREAD

**Issue by frodoe7** [fastify/fastify-cli#687]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I used Fastify CLI generate command to create the project

in my routes folder **/Auth/index.ts**
that is interpreted as route as /Auth
I need it to be /auth instead of /Auth

I need to keep the URL routes in lowercase and the folders in uppercase

What I reached to from research is to use
caseSensitive prop in Fastify config

however it did not work with the generated CLI project
looks, there's no typing support for it

<img width="544" alt="Screenshot 2023-12-30 at 7 43 36 PM" src="https://github.com/fastify/fastify/assets/2767001/ac7c4169-19ec-48ff-8c9c-dbf05890a0ed">

the response is `{"message":"Route GET:/auth not found","error":"Not Found","statusCode":404}`

have to be /Auth only

**Comment by mcollina** [comment]
Thanks for reporting! Fixing this should be easy, it’s likely we are missing some ways to move this option through.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by frodoe7** [comment]
@mcollina 

I fixed it in start.js file by changing that below line (|| instead of &&), however a bit busy to submit PR

```
-  if (opts.options && file.options) {
+  if (opts.options || file.options) {
     options = deepmerge(options, file.options)
   }
```

**Comment by dancastillo** [comment]
@frodoe7 if you update your script in `pacakge.json` to include `--options` should work

```
    "start": "fastify start -l info app.js --options",
    "dev": "fastify start -w -l info -P app.js --options"
```
<img width="379" alt="Screenshot 2024-01-01 at 8 59 33 PM" src="https://github.com/fastify/fastify-cli/assets/15673208/20c10704-ca3c-407d-8404-1f565ba6429a">

**Comment by frodoe7** [comment]
@dancastillo and where to add caseSensitive prop?
because I tested also with --options and did not work
the start.js file not pass the options

**Comment by climba03003** [comment]
You should provide the whole `index.ts` to show how you export the value.

**Comment by frodoe7** [comment]
@climba03003 
here's the whole app.ts file

```
import { join } from 'path';
import AutoLoad, {AutoloadPluginOptions} from '@fastify/autoload';
import { FastifyPluginAsync } from 'fastify';

export type AppOptions = {
  // Place your custom options for app below here.
  caseSensitive: boolean
} & Partial<AutoloadPluginOptions>;

// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {
    caseSensitive: false,
}

const app: FastifyPluginAsync<AppOptions> = async (
    fastify,
    opts
): Promise<void> => {
  // Place here your custom code!

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  });

  // This loads all plugins defined in routes
  // define your routes in one of these
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'routes'),
    options: opts
  });
};

export default app;
export { app, options }
```

**Comment by climba03003** [comment]
You should assign the `options` to `app.options` instead of exporting in the end.

**Comment by frodoe7** [comment]
options is not a member of app,

here we talk about the generated template from CLI, not when you use Fastify from scratch

<img width="697" alt="Screenshot 2024-01-02 at 5 02 55 PM" src="https://github.com/fastify/fastify-cli/assets/2767001/b32e13b9-16a5-4584-b2ce-846040135497">

**Comment by frodoe7** [comment]
@mcollina 
Can you look into that PR, should fix that issue?

https://github.com/fastify/fastify-cli/pull/691

**Comment by climba03003** [comment]
> options is not a member of app,

It is where this library expect the `options` to be but not `FastifyPluginAsync` types expect it.
Use `@ts-ignore` to see what is the outcome.

`fastify-cli` may not really fit all the expected types on `fastify`.

> here we talk about the generated template from CLI, not when you use Fastify from scratch

No one is talking about using fastify from scratch.

**Comment by frodoe7** [comment]
@climba03003 

Testes with ts-ignore
It's not a fix for the issue

**Comment by climba03003** [comment]
Have you also use the `--options` flag when starting the application?

**Comment by frodoe7** [comment]
@climba03003 Still not works and not a solution, did you test that solution by yourself?

**Comment by dancastillo** [comment]
@frodoe7 here is [demo repo](https://github.com/dancastillo/demo-fastify-ts-cli) with working example. Specific changes were in this [commit](https://github.com/dancastillo/demo-fastify-ts-cli/commit/fb614e6f173b8d3659a216a380d18282c5039e64)

**Comment by climba03003** [comment]
There is two people checked the library is working correctly. Only you are the person that say it is not working.
Please provide a reproducible repository like what [dancastillo](https://github.com/dancastillo) did.

@mcollina I would say there is no `bug` here, may be misconfiguration. However, I don't have permission to this repository. Could you helps to remove both `bug` and `first good issue` unless a proper `reproducible repository` is provided. Thanks.

**Comment by frodoe7** [comment]
@climba03003 really? Okay

It's still not working with your suggestion, it worked only when I implemented that change https://github.com/fastify/fastify-cli/issues/687#issuecomment-1872960384

anyway, I used patch-package to apply that change, in case no intention to fix it

**Comment by climba03003** [comment]
> It's still not working with your suggestion

Just saying it is not working do not helps to move thing forward.
Providing a  `reproducible repository` is what we would like to see and investigate.

**Comment by frodoe7** [comment]
@climba03003 

It worked when I added `--options` in the **dev:start** instead of **dev**
in package.json

**Comment by climba03003** [comment]
I don't know why you added in `dev` in first place.
My git diff is showing it should be added in `dev:start` and `start`.
Anyway, it works in your side now.
