### ISSUE TITLE
Generating project does not work with yarn

### ISSUE THREAD

**Issue by tiswrt** [fastify/fastify-cli#69]
Hello!

Generating a new project with yarn does not work, because yarn does not include a scripts property to the package.json.

```
pkg.scripts.test = 'standard && tap test/*.test.js test/*/*.test.js test/*/*/*.test.js'
                     ^
TypeError: Cannot set property 'test' of undefined
```

works fine with npm

**Comment by mcollina** [comment]
As you can imagine we are not yarn users! Would you mind sending us a PR?
