### ISSUE TITLE
c8 dependency is not added with fastify generate project_name --lang=ts

### ISSUE THREAD

**Issue by jebarpg** [fastify/fastify-cli#702]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4

### Node.js version

21.6.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Clear Linux OS installed version 40410

### Description

Had to manually install the c8 isn't in the devdependencies list when generating a typescript boilerplate project

### Steps to Reproduce

fastify generate test --lang=ts

### Expected Behavior

expected to have c8 in the devDependencies

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
