### ISSUE TITLE
Does Platformatic Replace fastify-cli ?

### ISSUE THREAD

**Issue by zoulou00** [fastify/fastify-cli#718]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi,

Is Platformatic intended to replace fastify-cli? 
If so, would you recommend migrating existing projects to Platformatic? 

Thanks,

**Comment by mcollina** [comment]
Platformatic does way more than fastify-cli, and we plan to do even more.
fastify-cli goal is to be a lightweight tool.

I would _personally_ recommend folks to try out Platformatic, but fastify-cli is awesome too.
