### ISSUE TITLE
Support ESM logging-module

### ISSUE THREAD

**Issue by segevfiner** [fastify/fastify-cli#760]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently the logging-module imported when using `-L/--logging-module` flag to `start` is imported using `require`, which is  annoying in an otherwise ESM only project. It should support using `import` the same as used for the main plugin as well.

### Motivation

Using a logging-module that is ESM, in a project that is also otherwise ESM only.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
