### ISSUE TITLE
TypeScript type augmentations not visible in tests with ESM modules

### ISSUE THREAD

**Issue by MatthewDahl** [fastify/fastify-cli#781]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

7.0.1

### Node.js version

20.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

macOS 15.1.1, build: 24B91

### Description

# TypeScript type augmentations not visible in tests with ESM modules

## Problem
When using ESM modules (`--esm`) with TypeScript (`--lang=ts`), plugin type augmentations aren't visible during test execution. This specifically affects projects where plugins depend on other plugins' type augmentations, causing runtime errors in tests despite TypeScript compilation succeeding.

## Reproduction Case
1. Create a new project:
```bash
fastify generate my-app --esm --lang=ts
```

2. Add a base plugin with type augmentations:
```typescript
// src/plugins/config.ts
import fp from 'fastify-plugin'

export interface Config {
  value: string
}

export default fp(async (fastify) => {
  fastify.decorate('config', { value: 'test' })
}, { name: 'config' })

declare module 'fastify' {
  interface FastifyInstance {
    config: Config
  }
}
```

3. Add a dependent plugin that uses the config type:
```typescript
// src/plugins/feature.ts
import fp from 'fastify-plugin'

export default fp(async (fastify) => {
  const configValue = fastify.config.value
  fastify.decorate('feature', { configValue })
}, {
  name: 'feature',
  dependencies: ['config']
})

declare module 'fastify' {
  interface FastifyInstance {
    feature: {
      configValue: string
    }
  }
}
```

4. Add a test that uses the plugin types:
```typescript
// test/plugins/feature.test.ts
import { test } from 'node:test'
import * as assert from 'node:assert'
import { build } from '../helper.js'

test('feature plugin type augmentations', async (t) => {
  const app = await build(t)

  // This line should cause TypeScript errors without proper type augmentations
  const value: string = app.config.value
  assert.equal(value, 'test')

  // This should also cause TypeScript errors
  const configValue: string = app.feature.configValue
  assert.equal(configValue, 'test')
})
```

5. Run the tests:
```bash
npm test
```

The test fails with:
```
✖ feature plugin type augmentations
  TypeError [Error]: Cannot read properties of undefined (reading 'value')
      at TestContext.<anonymous> (file:///path/to/test/plugins/feature.test.ts:6:30)
```

## Actual Behavior
- TypeScript compilation passes (types are visible)
- But runtime access to plugin decorations fails
- Plugin dependencies not properly loaded in test environment despite:
  - Having proper plugin names
  - Using `FASTIFY_AUTOLOAD_TYPESCRIPT=1`
  - Types being available at compile time

## Technical Details
- This is specific to ESM modules due to stricter module boundaries
- Only affects test execution (development/production work fine)
- Related to how `fastify-cli/helper.js` builds test instances
- Type augmentations work at compile time but plugins don't load at runtime
- Plugin dependency order works in main app but not in tests

## Current Workaround
We currently need to manually import all plugin files in tests to make their type augmentations visible. This requires additional setup and maintenance, especially as plugin dependencies grow.

## Additional Context
- Node.js version: v20.x
- TypeScript version: 5.x
- fastify-cli version: 7.x
- ESM modules enabled
- Using TypeScript with `"module": "NodeNext"`

### Link to code that reproduces the bug

https://github.com/MatthewDahl/fastify-esm-types-repro

### Expected Behavior

- Type augmentations from all plugins should be available in tests
- Plugin dependencies should have their types properly resolved
- Plugin decorations should be available at runtime in tests
- Same behavior as CommonJS modules

**Comment by jean-michelet** [comment]
Doesn't look like a TS problem right?
```ts
export default fp(async (fastify) => {
  fastify.decorate('config', { value: 'test' })
}, { name: 'config' })
```

**Comment by MatthewDahl** [comment]
Thank you for the suggestion about adding plugin names. I've updated the reproduction repository with:
1. Named plugins (`config` and `feature`)
2. A more focused test that demonstrates the issue

The test now shows an interesting behavior:
- TypeScript compilation passes (the types are visible)
- But at runtime, the plugins aren't loaded (`app.config` is undefined)

This happens despite:
- Having proper plugin names
- Using `FASTIFY_AUTOLOAD_TYPESCRIPT=1`
- Types being available at compile time

You can see the updated example at https://github.com/MatthewDahl/fastify-esm-types-repro. The failing test provides a clearer demonstration of the runtime loading issue.

I've also updated the issue description to reflect these changes and the current error message.

**Comment by mcollina** [comment]
If you want to access decorators, you need to wrap https://github.com/MatthewDahl/fastify-esm-types-repro/blob/677d64b75e0761df8b4ea50c49ff08ad21685573/src/app.ts#L18 with fastifyPlugin.

**Comment by jean-michelet** [comment]
We merged a PR to automate this already, this is in the doc:
```ts
const app = await build(argv, {
    extraParam: 'foo',
    skipOverride: true // If you want your application to be registered with fastify-plugin
  })
```

**Comment by MatthewDahl** [comment]
Thank you @mcollina and @jean-michelet! Adding `skipOverride: true` to the test config resolved the issue. I've updated the reproduction repository to include this change, and it's working perfectly now.

@mcollina regarding your last question about generated tests not including this by default - that's what made me curious. Is there a specific reason `skipOverride` isn't enabled by default for tests? I'm wondering if relying on registered plugins in tests is considered an anti-pattern, or if there are other considerations I should be aware of when testing plugin decorations.

Thanks again for the help!

**Comment by jean-michelet** [comment]
> Is there a specific reason skipOverride isn't enabled by default for tests?

Long story short: 
Originally, the app was wrapped in `fp`, but a changed has been implemented at some point and it wasn't anymore, so [we introduced](https://github.com/fastify/fastify-cli/pull/742) this option to allow users to override their app if necessary.

I think I'll push a PR tomorrow to update the template, we should generate an example of use in the code to reduce confusion about it.
