### ISSUE TITLE
fastify start: options not picked up from  ESM exported options 

### ISSUE THREAD

**Issue by seriousme** [fastify/fastify-cli#782]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

fastify-cli 7.1.0

### Node.js version

22.11.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

12

### Description

When exporting the options object using ESM as described in README.md the options are not applied by `fastify start`
i.e.:

When I run `fastify start example.js`
where example.js  is copied from [README.md](https://github.com/fastify/fastify-cli/blob/master/README.md):
```javascript
export default async function plugin(fastify, options) {
	// Both `/foo` and `/foo/` are registered
	fastify.get("/foo/", async function (req, reply) {
		return "foo";
	});
}

export const options = {
	ignoreTrailingSlash: true,
};
```
and then use: `curl http://localhost:3000/foo`
the answer is: `{"message":"Route GET:/foo not found","error":"Not Found","statusCode":404}`
while `curl http://localhost:3000/foo/` returns `foo`

Kind regards,
Hans

### Expected Behavior

I expected `ignoringSlash` to be applied.

**Comment by seriousme** [comment]
I did some digging and the problem is in this section:

https://github.com/fastify/fastify-cli/blob/381e810b583660421e7f9f9408151c904ab55693/start.js#L164-L166

Before:
```javascript
{
  file: [Module: null prototype] {
    default: [AsyncFunction: plugin],
    options: { ignoreTrailingSlash: true }
  }
}
{ options: { logger: { level: 'fatal' }, pluginTimeout: 10000 } }
```

and after:

```javascript
{
  file: [Module: null prototype] {
    default: [AsyncFunction: plugin],
    options: { ignoreTrailingSlash: true }
  }
}
{ options: { logger: { level: 'fatal' }, pluginTimeout: 10000 } }
```
where one would expect:
```javascript
{
  options: {
    logger: { level: 'fatal' },
    pluginTimeout: 10000,
    ignoreTrailingSlash: true
  }
}
```

**Comment by jean-michelet** [comment]
Can you plz show what you are logging precisely?
Such a bug in `deepmerge` is very unlikely.

Did you use the flag `--options`?

**Comment by seriousme** [comment]
Just plain simple console.log

```javascript
  console.log({options});
  console.log({file});

// next line is original line 164 of start.js
  if (opts.options && file.options) {
    options = deepmerge(options, file.options)
  }

  console.log({options});
  console.log({file});
```
https://github.com/fastify/fastify-cli/blob/381e810b583660421e7f9f9408151c904ab55693/start.js#L164-L166

I' m starting the server with `npx fastify start example.js` in a folder which contains a package.json containing `type: module`

The weird thing is that when I try this in isolation:

```javascript
import Deepmerge from "@fastify/deepmerge";

const deepmerge = Deepmerge({
	cloneProtoObject(obj) {
		return obj;
	},
});
const file = await import("./example.js");
let options = {
	logger: { level: "fatal" },
	pluginTimeout: 10000,
};

console.log(file);
options = deepmerge(options, file.options);
console.log({ options });
```

The result is as expected:
```javascript
[Module: null prototype] {
  default: [AsyncFunction: plugin],
  options: { ignoreTrailingSlash: true }
}
{
  options: {
    logger: { level: 'fatal' },
    pluginTimeout: 10000,
    ignoreTrailingSlash: true
  }
}
```
So it feels a bit like a heisenbug :-(

Kind regards,
Hans
