### ISSUE TITLE
Consider removing linter tasks from the generated project

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify-cli#94]
Currently the cli generates a project with the `standardjs` linting. However, most people is probably using eslint (I suppose). So I believe that the cli should support one of the following:

a) A generator option with eslint config  (maybe just use airbnb preset)
b) A bare and unopinionated generator in terms of linting (Simpler)

**Comment by mcollina** [comment]
I do not think we should add options. The moment we start adding options we will get:

- choice of linter
- choice of testing framework
- choice between callbacks and async/await
- choice of database
- choice of template engine
- ...

The generator _is_ opinionated. It is how @delvedor and myself (and possibly others from @fastify/fastify) think an application should be structured. You can structure your application the way you prefer (even all the code in one file).

What do you mean by unopinionated? Should we just remove the `linter` task?

**Comment by cemremengu** [comment]
Yes, you are right. One of the things I like about fastify that it is not bloated so definitely not a fan of the choice tree you mentioned. 

By unopinionated, I only mean the linting choice of  `standardjs` in the generated project. I can imagine many people editing/changing `standardjs` parts in `devDependecies` and `scripts` after creating the project. 

Since linting is purely based on choice at the moment in JS ecosystem, it may be a good idea to describe linting task integration in readme instead of forcing it to the cli.

**Comment by mcollina** [comment]
This is interesting, ok!

@delvedor what do you think? It might be good to do!

**Comment by delvedor** [comment]
I agree that directly add `standard` as a dependency is opinionated, but if we make it optional, what about the generated code? It follows standard's rules.

**Comment by mcollina** [comment]
I would keep the code as it is right now.
Il giorno ven 24 ago 2018 alle 14:29 Tomas Della Vedova <
notifications@github.com> ha scritto:

**Comment by cemremengu** [comment]
I think having the code following standard's rules should be fine, formatters/linters can change them automatically. 

After all, you need to be opinionated on the generated code based on the rule set of choice. There seems to be no other way.

**Comment by allevo** [comment]
I'm 👎 to remove.
`standard` as a dependency is opinionated as the generated project structure is.
If `generate` command reflects what we (???) suggests, the linting script should be included too.

Anyway I'm not blocking

**Comment by jsumners** [comment]
I think that if you have strong opinions about project structure, which includes the linter used, then a third party code generator is not for you.

**Comment by mcollina** [comment]
I think removing the default linter is good. I've used this in several workshops, and the vast majority of the attendees struggled _a lot_ with the linter.

**Comment by delvedor** [comment]
> I've used this in several workshops, and the vast majority of the attendees struggled a lot with the linter.

Same here, the `lint` script was added specifically for this purpose, but it didn't help too much.

**Comment by mcollina** [comment]
This is landed in #95.
